syntax = "proto3";
package scalar.covenant.v1beta1;

import "gogoproto/gogo.proto";

option go_package = "github.com/scalarorg/scalar-core/x/covenant/types";
option (gogoproto.goproto_getters_all) = false;

enum Phase {
  option (gogoproto.goproto_enum_prefix) = false;

  PHASE_PREPARING = 0 [ (gogoproto.enumvalue_customname) = "Preparing" ];
  PHASE_EXECUTING = 1 [ (gogoproto.enumvalue_customname) = "Executing" ];
  PHASE_SWITCHING = 2 [ (gogoproto.enumvalue_customname) = "Switching" ];
}

message UTXO {
  bytes txid = 1 [
    (gogoproto.nullable) = false,
    (gogoproto.customtype) =
        "github.com/scalarorg/scalar-core/x/chains/types.Hash",
    (gogoproto.customname) = "TxID"
  ];
  uint32 vout = 2;
  bytes script_pubkey = 3;
  uint64 amount_in_sats = 4;
}

message RedeemSession {
  uint64 sequence = 1;
  Phase current_phase = 2;
  bytes last_redeem_tx = 3 [
    (gogoproto.nullable) = false,
    (gogoproto.customtype) =
        "github.com/scalarorg/scalar-core/x/chains/types.Hash",
    (gogoproto.customname) = "TxID"
  ];
  repeated UTXO utxos = 4;
}