syntax = "proto3";
package scalar.covenant.v1beta1;

import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "google/protobuf/any.proto";
import "scalar/covenant/exported/v1beta1/types.proto";
import "scalar/multisig/v1beta1/types.proto";

option go_package = "github.com/scalarorg/scalar-core/x/covenant/types";

message PsbtMultiSig {
  option (gogoproto.stable_marshaler) = true;

  string key_id = 1 [
    (gogoproto.customname) = "KeyID",
    (gogoproto.casttype) =
        "github.com/scalarorg/scalar-core/x/multisig/exported.KeyID"
  ];
  repeated bytes multi_psbt = 2
      [ (gogoproto.casttype) =
            "github.com/scalarorg/scalar-core/x/covenant/exported.Psbt" ];
  map<string, scalar.covenant.exported.v1beta1.ListOfTapScriptSigsMap>
      participant_list_tap_script_sigs = 3;
  repeated bytes finalized_txs = 4;
}

message SigningSession {
  option (gogoproto.stable_marshaler) = true;

  uint64 id = 1 [ (gogoproto.customname) = "ID" ];
  PsbtMultiSig psbt_multi_sig = 2 [ (gogoproto.nullable) = false ];
  exported.v1beta1.PsbtState state = 3;
  scalar.multisig.v1beta1.Key key = 4 [ (gogoproto.nullable) = false ];
  int64 expires_at = 5;
  int64 completed_at = 6;
  int64 grace_period = 7;
  string module = 8;
  google.protobuf.Any module_metadata = 9
      [ (cosmos_proto.accepts_interface) =
            "github.com/cosmos/codec/ProtoMarshaler" ];
}

message BasicPollMetadata {
  string chain = 1
      [ (gogoproto.casttype) =
            "github.com/scalarorg/scalar-core/x/nexus/exported.ChainName" ];
  bytes data = 2;
}

message BasicPollFailed {
  string chain = 1
      [ (gogoproto.casttype) =
            "github.com/scalarorg/scalar-core/x/nexus/exported.ChainName" ];
  bytes data = 2;
  string poll_id = 3 [
    (gogoproto.customname) = "PollID",
    (gogoproto.customtype) =
        "github.com/scalarorg/scalar-core/x/vote/exported.PollID",
    (gogoproto.nullable) = false
  ];
}

message BasicPollExpired {
  string chain = 1
      [ (gogoproto.casttype) =
            "github.com/scalarorg/scalar-core/x/nexus/exported.ChainName" ];
  bytes data = 2;
  string poll_id = 3 [
    (gogoproto.customname) = "PollID",
    (gogoproto.customtype) =
        "github.com/scalarorg/scalar-core/x/vote/exported.PollID",
    (gogoproto.nullable) = false
  ];
}

message BasicPollCompleted {
  string chain = 1
      [ (gogoproto.casttype) =
            "github.com/scalarorg/scalar-core/x/nexus/exported.ChainName" ];
  bytes data = 2;
  string poll_id = 3 [
    (gogoproto.customname) = "PollID",
    (gogoproto.customtype) =
        "github.com/scalarorg/scalar-core/x/vote/exported.PollID",
    (gogoproto.nullable) = false
  ];
}

message BasicPollNoEventsConfirmed {
  string chain = 1
      [ (gogoproto.casttype) =
            "github.com/scalarorg/scalar-core/x/nexus/exported.ChainName" ];
  bytes data = 2;
  string poll_id = 3 [
    (gogoproto.customname) = "PollID",
    (gogoproto.customtype) =
        "github.com/scalarorg/scalar-core/x/vote/exported.PollID",
    (gogoproto.nullable) = false
  ];
}

