// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scalar/covenant/exported/v1beta1/custodian.proto

package exported

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Custodian_Unspecified Status = 0
	Custodian_Activated   Status = 1
	Custodian_Deactivated Status = 2
	Custodian_Pending     Status = 3
)

var Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_ACTIVATED",
	2: "STATUS_DEACTIVATED",
	3: "STATUS_PENDING",
}

var Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_ACTIVATED":   1,
	"STATUS_DEACTIVATED": 2,
	"STATUS_PENDING":     3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07065a76ceb76d18, []int{0}
}

// Custodian represents an individual custodian configuration
type Custodian struct {
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ValAddress    string `protobuf:"bytes,2,opt,name=val_address,json=valAddress,proto3" json:"val_address,omitempty"`
	BitcoinPubkey []byte `protobuf:"bytes,3,opt,name=bitcoin_pubkey,json=bitcoinPubkey,proto3" json:"bitcoin_pubkey,omitempty"`
	// "0215da913b3e87b4932b1e1b87d9667c28e7250aa0ed60b3a31095f541e1641488"
	Status      Status `protobuf:"varint,4,opt,name=status,proto3,enum=scalar.covenant.exported.v1beta1.Status" json:"status,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *Custodian) Reset()         { *m = Custodian{} }
func (m *Custodian) String() string { return proto.CompactTextString(m) }
func (*Custodian) ProtoMessage()    {}
func (*Custodian) Descriptor() ([]byte, []int) {
	return fileDescriptor_07065a76ceb76d18, []int{0}
}
func (m *Custodian) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Custodian) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Custodian.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Custodian) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Custodian.Merge(m, src)
}
func (m *Custodian) XXX_Size() int {
	return m.Size()
}
func (m *Custodian) XXX_DiscardUnknown() {
	xxx_messageInfo_Custodian.DiscardUnknown(m)
}

var xxx_messageInfo_Custodian proto.InternalMessageInfo

// CustodianGroup represents a group of custodians with their configuration
// uid is used as identity of the group, btc_pubkey is change by list of
// custodians
type CustodianGroup struct {
	// the UID is unique, to distinguish between custodian groups
	UID           string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BitcoinPubkey []byte `protobuf:"bytes,3,opt,name=bitcoin_pubkey,json=bitcoinPubkey,proto3" json:"bitcoin_pubkey,omitempty"`
	// "tb1p07q440mdl4uyywns325dk8pvjphwety3psp4zvkngtjf3z3hhr2sfar3hv"
	Quorum      uint32       `protobuf:"varint,4,opt,name=quorum,proto3" json:"quorum,omitempty"`
	Status      Status       `protobuf:"varint,5,opt,name=status,proto3,enum=scalar.covenant.exported.v1beta1.Status" json:"status,omitempty"`
	Description string       `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Custodians  []*Custodian `protobuf:"bytes,7,rep,name=custodians,proto3" json:"custodians,omitempty"`
}

func (m *CustodianGroup) Reset()         { *m = CustodianGroup{} }
func (m *CustodianGroup) String() string { return proto.CompactTextString(m) }
func (*CustodianGroup) ProtoMessage()    {}
func (*CustodianGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_07065a76ceb76d18, []int{1}
}
func (m *CustodianGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodianGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodianGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodianGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodianGroup.Merge(m, src)
}
func (m *CustodianGroup) XXX_Size() int {
	return m.Size()
}
func (m *CustodianGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodianGroup.DiscardUnknown(m)
}

var xxx_messageInfo_CustodianGroup proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("scalar.covenant.exported.v1beta1.Status", Status_name, Status_value)
	proto.RegisterType((*Custodian)(nil), "scalar.covenant.exported.v1beta1.Custodian")
	proto.RegisterType((*CustodianGroup)(nil), "scalar.covenant.exported.v1beta1.CustodianGroup")
}

func init() {
	proto.RegisterFile("scalar/covenant/exported/v1beta1/custodian.proto", fileDescriptor_07065a76ceb76d18)
}

var fileDescriptor_07065a76ceb76d18 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0x6e, 0xd3, 0x4c,
	0x14, 0xc7, 0x3d, 0x49, 0x9a, 0xaa, 0x93, 0xaf, 0x51, 0xbe, 0x81, 0x82, 0x9b, 0x85, 0x6b, 0x55,
	0x42, 0x32, 0xa0, 0xda, 0xa4, 0x70, 0x00, 0xdc, 0xd8, 0x54, 0x16, 0x52, 0x14, 0x39, 0x09, 0x0b,
	0x36, 0xd1, 0xd8, 0x1e, 0xcc, 0x88, 0xc4, 0x63, 0xec, 0xb1, 0x55, 0x6e, 0x80, 0xb2, 0xe2, 0x02,
	0x59, 0x71, 0x00, 0xae, 0x51, 0x09, 0x09, 0x75, 0xc9, 0x0a, 0x41, 0x72, 0x11, 0x54, 0xdb, 0x71,
	0x2c, 0xba, 0x28, 0x0b, 0x76, 0xcf, 0x7f, 0xbf, 0x9f, 0xdf, 0xfb, 0x8d, 0x35, 0xf0, 0x49, 0xec,
	0xe2, 0x19, 0x8e, 0x34, 0x97, 0xa5, 0x24, 0xc0, 0x01, 0xd7, 0xc8, 0x45, 0xc8, 0x22, 0x4e, 0x3c,
	0x2d, 0xed, 0x39, 0x84, 0xe3, 0x9e, 0xe6, 0x26, 0x31, 0x67, 0x1e, 0xc5, 0x81, 0x1a, 0x46, 0x8c,
	0x33, 0x24, 0xe7, 0x84, 0xba, 0x21, 0xd4, 0x0d, 0xa1, 0x16, 0x44, 0xf7, 0xae, 0xcf, 0x7c, 0x96,
	0x35, 0x6b, 0xd7, 0x55, 0xce, 0x1d, 0x7f, 0x05, 0x70, 0xaf, 0xbf, 0xf9, 0x16, 0x42, 0xb0, 0x11,
	0xe0, 0x39, 0x11, 0x81, 0x0c, 0x94, 0x3d, 0x3b, 0xab, 0xd1, 0x11, 0x6c, 0xa5, 0x78, 0x36, 0xc5,
	0x9e, 0x17, 0x91, 0x38, 0x16, 0x6b, 0xd9, 0x2b, 0x98, 0xe2, 0x99, 0x9e, 0x27, 0xe8, 0x01, 0x6c,
	0x3b, 0x94, 0xbb, 0x8c, 0x06, 0xd3, 0x30, 0x71, 0xde, 0x91, 0x0f, 0x62, 0x5d, 0x06, 0xca, 0x7f,
	0xf6, 0x7e, 0x91, 0x0e, 0xb3, 0x10, 0x3d, 0x87, 0xcd, 0x98, 0x63, 0x9e, 0xc4, 0x62, 0x43, 0x06,
	0x4a, 0xfb, 0x54, 0x51, 0x6f, 0x5b, 0x59, 0x1d, 0x65, 0xfd, 0x76, 0xc1, 0x21, 0x19, 0xb6, 0x3c,
	0x12, 0xbb, 0x11, 0x0d, 0x39, 0x65, 0x81, 0xb8, 0x93, 0x6d, 0x52, 0x8d, 0x8e, 0xbf, 0xd4, 0x60,
	0xbb, 0xb4, 0x39, 0x8f, 0x58, 0x12, 0xa2, 0x43, 0x58, 0x4f, 0xa8, 0x97, 0x1b, 0x9d, 0xed, 0xae,
	0x7e, 0x1c, 0xd5, 0x27, 0x96, 0x61, 0x5f, 0x67, 0xa5, 0x6d, 0xad, 0x62, 0xfb, 0x97, 0x32, 0xf7,
	0x60, 0xf3, 0x7d, 0xc2, 0xa2, 0x64, 0x9e, 0xc9, 0xec, 0xdb, 0xc5, 0x53, 0x45, 0x72, 0xe7, 0xdf,
	0x48, 0x36, 0x6f, 0x48, 0xa2, 0x97, 0x10, 0x96, 0x7f, 0x3f, 0x16, 0x77, 0xe5, 0xba, 0xd2, 0x3a,
	0x7d, 0x7c, 0xfb, 0x9c, 0xf2, 0x5c, 0xec, 0x0a, 0xfe, 0xe8, 0x1b, 0x80, 0xcd, 0x7c, 0x03, 0xd4,
	0x83, 0x68, 0x34, 0xd6, 0xc7, 0x93, 0xd1, 0x74, 0x32, 0x18, 0x0d, 0xcd, 0xbe, 0xf5, 0xc2, 0x32,
	0x8d, 0x8e, 0xd0, 0x3d, 0x5c, 0x2c, 0xe5, 0x83, 0x92, 0x9e, 0x4e, 0x82, 0x38, 0x24, 0x2e, 0x7d,
	0x43, 0x89, 0x87, 0x4e, 0x60, 0xa7, 0x40, 0xf4, 0xfe, 0xd8, 0x7a, 0xa5, 0x8f, 0x4d, 0xa3, 0x03,
	0xba, 0xf7, 0x17, 0x4b, 0xf9, 0xce, 0x16, 0xd0, 0x5d, 0x4e, 0x53, 0xcc, 0x89, 0x57, 0x99, 0x60,
	0x98, 0x5b, 0xa0, 0xf6, 0xe7, 0x04, 0x83, 0xe0, 0x12, 0x79, 0x08, 0xdb, 0x05, 0x32, 0x34, 0x07,
	0x86, 0x35, 0x38, 0xef, 0xd4, 0xbb, 0x07, 0x8b, 0xa5, 0xfc, 0xff, 0xb6, 0x7d, 0x48, 0x02, 0x8f,
	0x06, 0x7e, 0xb7, 0xf1, 0xf1, 0xb3, 0x24, 0x9c, 0xd9, 0x97, 0xbf, 0x24, 0xe1, 0x72, 0x25, 0x81,
	0xab, 0x95, 0x04, 0x7e, 0xae, 0x24, 0xf0, 0x69, 0x2d, 0x09, 0x57, 0x6b, 0x49, 0xf8, 0xbe, 0x96,
	0x84, 0xd7, 0xcf, 0x7c, 0xca, 0xdf, 0x26, 0x8e, 0xea, 0xb2, 0xb9, 0x96, 0x9f, 0x18, 0x8b, 0xfc,
	0xa2, 0x3a, 0x71, 0x59, 0x44, 0xb4, 0x8b, 0x9b, 0x97, 0xce, 0x69, 0x66, 0x77, 0xe5, 0xe9, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xbe, 0x64, 0x10, 0x97, 0x03, 0x00, 0x00,
}

func (m *Custodian) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Custodian) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Custodian) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintCustodian(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Status != 0 {
		i = encodeVarintCustodian(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BitcoinPubkey) > 0 {
		i -= len(m.BitcoinPubkey)
		copy(dAtA[i:], m.BitcoinPubkey)
		i = encodeVarintCustodian(dAtA, i, uint64(len(m.BitcoinPubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintCustodian(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCustodian(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodianGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodianGroup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodianGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Custodians) > 0 {
		for iNdEx := len(m.Custodians) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Custodians[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCustodian(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintCustodian(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x32
	}
	if m.Status != 0 {
		i = encodeVarintCustodian(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.Quorum != 0 {
		i = encodeVarintCustodian(dAtA, i, uint64(m.Quorum))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BitcoinPubkey) > 0 {
		i -= len(m.BitcoinPubkey)
		copy(dAtA[i:], m.BitcoinPubkey)
		i = encodeVarintCustodian(dAtA, i, uint64(len(m.BitcoinPubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCustodian(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UID) > 0 {
		i -= len(m.UID)
		copy(dAtA[i:], m.UID)
		i = encodeVarintCustodian(dAtA, i, uint64(len(m.UID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCustodian(dAtA []byte, offset int, v uint64) int {
	offset -= sovCustodian(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Custodian) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCustodian(uint64(l))
	}
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovCustodian(uint64(l))
	}
	l = len(m.BitcoinPubkey)
	if l > 0 {
		n += 1 + l + sovCustodian(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovCustodian(uint64(m.Status))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovCustodian(uint64(l))
	}
	return n
}

func (m *CustodianGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UID)
	if l > 0 {
		n += 1 + l + sovCustodian(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCustodian(uint64(l))
	}
	l = len(m.BitcoinPubkey)
	if l > 0 {
		n += 1 + l + sovCustodian(uint64(l))
	}
	if m.Quorum != 0 {
		n += 1 + sovCustodian(uint64(m.Quorum))
	}
	if m.Status != 0 {
		n += 1 + sovCustodian(uint64(m.Status))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovCustodian(uint64(l))
	}
	if len(m.Custodians) > 0 {
		for _, e := range m.Custodians {
			l = e.Size()
			n += 1 + l + sovCustodian(uint64(l))
		}
	}
	return n
}

func sovCustodian(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCustodian(x uint64) (n int) {
	return sovCustodian(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Custodian) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCustodian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Custodian: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Custodian: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BitcoinPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BitcoinPubkey = append(m.BitcoinPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.BitcoinPubkey == nil {
				m.BitcoinPubkey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCustodian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCustodian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodianGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCustodian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodianGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodianGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BitcoinPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BitcoinPubkey = append(m.BitcoinPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.BitcoinPubkey == nil {
				m.BitcoinPubkey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quorum", wireType)
			}
			m.Quorum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quorum |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Custodians", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCustodian
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCustodian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Custodians = append(m.Custodians, &Custodian{})
			if err := m.Custodians[len(m.Custodians)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCustodian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCustodian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCustodian(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCustodian
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCustodian
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCustodian
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCustodian
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCustodian
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCustodian        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCustodian          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCustodian = fmt.Errorf("proto: unexpected end of group")
)
