// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scalar/covenant/v1beta1/command.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	github_com_scalarorg_scalar_core_x_chains_exported "github.com/scalarorg/scalar-core/x/chains/exported"
	github_com_scalarorg_scalar_core_x_multisig_exported "github.com/scalarorg/scalar-core/x/multisig/exported"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CommandStatus int32

const (
	CommandNonExistent CommandStatus = 0
	CommandSigning     CommandStatus = 1
	CommandAborted     CommandStatus = 2
	CommandSigned      CommandStatus = 3
)

var CommandStatus_name = map[int32]string{
	0: "COMMAND_STATUS_UNSPECIFIED",
	1: "COMMAND_STATUS_SIGNING",
	2: "COMMAND_STATUS_ABORTED",
	3: "COMMAND_STATUS_SIGNED",
}

var CommandStatus_value = map[string]int32{
	"COMMAND_STATUS_UNSPECIFIED": 0,
	"COMMAND_STATUS_SIGNING":     1,
	"COMMAND_STATUS_ABORTED":     2,
	"COMMAND_STATUS_SIGNED":      3,
}

func (x CommandStatus) String() string {
	return proto.EnumName(CommandStatus_name, int32(x))
}

func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_93c39df493b7beed, []int{0}
}

type CommandMetadata struct {
	ID        []byte                                                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data      []byte                                                     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	SigHash   github_com_scalarorg_scalar_core_x_chains_exported.Hash    `protobuf:"bytes,3,opt,name=sig_hash,json=sigHash,proto3,customtype=github.com/scalarorg/scalar-core/x/chains/exported.Hash" json:"sig_hash"`
	Status    CommandStatus                                              `protobuf:"varint,4,opt,name=status,proto3,enum=scalar.covenant.v1beta1.CommandStatus" json:"status,omitempty"`
	KeyID     github_com_scalarorg_scalar_core_x_multisig_exported.KeyID `protobuf:"bytes,5,opt,name=key_id,json=keyId,proto3,casttype=github.com/scalarorg/scalar-core/x/multisig/exported.KeyID" json:"key_id,omitempty"`
	Signature *types.Any                                                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *CommandMetadata) Reset()         { *m = CommandMetadata{} }
func (m *CommandMetadata) String() string { return proto.CompactTextString(m) }
func (*CommandMetadata) ProtoMessage()    {}
func (*CommandMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_93c39df493b7beed, []int{0}
}
func (m *CommandMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommandMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommandMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommandMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandMetadata.Merge(m, src)
}
func (m *CommandMetadata) XXX_Size() int {
	return m.Size()
}
func (m *CommandMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CommandMetadata proto.InternalMessageInfo

func (m *CommandMetadata) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *CommandMetadata) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CommandMetadata) GetStatus() CommandStatus {
	if m != nil {
		return m.Status
	}
	return CommandNonExistent
}

func (m *CommandMetadata) GetKeyID() github_com_scalarorg_scalar_core_x_multisig_exported.KeyID {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *CommandMetadata) GetSignature() *types.Any {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("scalar.covenant.v1beta1.CommandStatus", CommandStatus_name, CommandStatus_value)
	proto.RegisterType((*CommandMetadata)(nil), "scalar.covenant.v1beta1.CommandMetadata")
}

func init() {
	proto.RegisterFile("scalar/covenant/v1beta1/command.proto", fileDescriptor_93c39df493b7beed)
}

var fileDescriptor_93c39df493b7beed = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x6b, 0x13, 0x4d,
	0x1c, 0xc7, 0x77, 0xd3, 0x36, 0xcf, 0xd3, 0xd1, 0xd6, 0x38, 0xd4, 0xba, 0xee, 0x61, 0xb3, 0x08,
	0x96, 0x50, 0xec, 0x0e, 0xa9, 0xa0, 0xe0, 0x41, 0x49, 0xb2, 0x31, 0x2e, 0x25, 0x69, 0xd9, 0xa4,
	0x97, 0x1e, 0x1a, 0x26, 0xbb, 0xe3, 0xec, 0xd0, 0x64, 0x27, 0xec, 0x4c, 0x4a, 0xf6, 0x1d, 0x48,
	0x4e, 0x5e, 0x3d, 0xe4, 0xe4, 0x5b, 0xf0, 0x45, 0x14, 0x4f, 0x3d, 0x8a, 0x42, 0x90, 0xe4, 0x5d,
	0x78, 0x92, 0xec, 0x26, 0xb4, 0x95, 0x0a, 0xbd, 0xfd, 0x86, 0xef, 0xe7, 0xfb, 0xfb, 0xbb, 0x0b,
	0x9e, 0x09, 0x0f, 0x77, 0x71, 0x84, 0x3c, 0x7e, 0x4e, 0x42, 0x1c, 0x4a, 0x74, 0x5e, 0xec, 0x10,
	0x89, 0x8b, 0xc8, 0xe3, 0xbd, 0x1e, 0x0e, 0x7d, 0xab, 0x1f, 0x71, 0xc9, 0xe1, 0xe3, 0x14, 0xb3,
	0x96, 0x98, 0xb5, 0xc0, 0xf4, 0x2d, 0xca, 0x29, 0x4f, 0x18, 0x34, 0x8f, 0x52, 0x5c, 0x7f, 0x42,
	0x39, 0xa7, 0x5d, 0x82, 0x92, 0x57, 0x67, 0xf0, 0x01, 0xe1, 0x30, 0x5e, 0x4a, 0x1e, 0x17, 0x3d,
	0x2e, 0xda, 0xa9, 0x27, 0x7d, 0xa4, 0xd2, 0xd3, 0xcf, 0x2b, 0xe0, 0x41, 0x25, 0x2d, 0x5b, 0x27,
	0x12, 0xfb, 0x58, 0x62, 0xb8, 0x0d, 0x32, 0xcc, 0xd7, 0x54, 0x53, 0x2d, 0xdc, 0x2f, 0x67, 0xa7,
	0x93, 0x7c, 0xc6, 0xb1, 0xdd, 0x0c, 0xf3, 0x21, 0x04, 0xab, 0x73, 0x5d, 0xcb, 0xcc, 0x15, 0x37,
	0x89, 0xe1, 0x09, 0xf8, 0x5f, 0x30, 0xda, 0x0e, 0xb0, 0x08, 0xb4, 0x95, 0xc4, 0xf1, 0xf6, 0x62,
	0x92, 0x57, 0x7e, 0x4c, 0xf2, 0xaf, 0x28, 0x93, 0xc1, 0xa0, 0x63, 0x79, 0xbc, 0x87, 0xd2, 0x49,
	0x78, 0x44, 0x17, 0xd1, 0x9e, 0xc7, 0x23, 0x82, 0x86, 0xc8, 0x0b, 0x30, 0x0b, 0x05, 0x22, 0xc3,
	0x3e, 0x8f, 0x24, 0xf1, 0xad, 0xf7, 0x58, 0x04, 0xee, 0x7f, 0x82, 0xd1, 0x79, 0x00, 0xdf, 0x80,
	0xac, 0x90, 0x58, 0x0e, 0x84, 0xb6, 0x6a, 0xaa, 0x85, 0xcd, 0xfd, 0x1d, 0xeb, 0x1f, 0x1b, 0xb1,
	0x16, 0x13, 0x34, 0x13, 0xda, 0x5d, 0xb8, 0xe0, 0x29, 0xc8, 0x9e, 0x91, 0xb8, 0xcd, 0x7c, 0x6d,
	0xcd, 0x54, 0x0b, 0xeb, 0xe5, 0xda, 0x74, 0x92, 0x5f, 0x3b, 0x20, 0xb1, 0x63, 0xff, 0x9e, 0xe4,
	0x5f, 0xdf, 0xa1, 0xbd, 0xde, 0xa0, 0x2b, 0x99, 0x60, 0xf4, 0xaa, 0xc1, 0xc4, 0xed, 0xae, 0x9d,
	0x91, 0xd8, 0xf1, 0xe1, 0x29, 0x58, 0x17, 0x8c, 0x86, 0x58, 0x0e, 0x22, 0xa2, 0x65, 0x4d, 0xb5,
	0x70, 0x6f, 0x7f, 0xcb, 0x4a, 0xaf, 0x60, 0x2d, 0xaf, 0x60, 0x95, 0xc2, 0xb8, 0xbc, 0xfb, 0xed,
	0xeb, 0xde, 0xce, 0xb5, 0x7a, 0xe9, 0x05, 0x90, 0xc7, 0x7d, 0xe2, 0xa1, 0xa3, 0x39, 0x59, 0xc7,
	0x91, 0x08, 0x70, 0x97, 0x44, 0xee, 0x55, 0xca, 0xdd, 0x9f, 0x2a, 0xd8, 0xb8, 0x31, 0x19, 0x7c,
	0x09, 0xf4, 0xca, 0x61, 0xbd, 0x5e, 0x6a, 0xd8, 0xed, 0x66, 0xab, 0xd4, 0x3a, 0x6e, 0xb6, 0x8f,
	0x1b, 0xcd, 0xa3, 0x6a, 0xc5, 0x79, 0xe7, 0x54, 0xed, 0x9c, 0xa2, 0x6f, 0x8f, 0xc6, 0x26, 0x5c,
	0x58, 0x1a, 0x3c, 0xac, 0x0e, 0x99, 0x90, 0x24, 0x94, 0xd0, 0x02, 0xdb, 0x7f, 0xf9, 0x9a, 0x4e,
	0xad, 0xe1, 0x34, 0x6a, 0x39, 0x55, 0x87, 0xa3, 0xb1, 0xb9, 0xb9, 0x2c, 0xc3, 0x68, 0xc8, 0x42,
	0x7a, 0x0b, 0x5f, 0x2a, 0x1f, 0xba, 0xad, 0xaa, 0x9d, 0xcb, 0xdc, 0xe0, 0x4b, 0x9d, 0x64, 0x2d,
	0xf0, 0x39, 0x78, 0x74, 0x4b, 0xfe, 0xaa, 0x9d, 0x5b, 0xd1, 0x1f, 0x8e, 0xc6, 0xe6, 0xc6, 0xb5,
	0xf4, 0xc4, 0xd7, 0x57, 0x3f, 0x7e, 0x31, 0x94, 0xf2, 0xc1, 0xc5, 0xd4, 0x50, 0x2f, 0xa7, 0x86,
	0xfa, 0x6b, 0x6a, 0xa8, 0x9f, 0x66, 0x86, 0x72, 0x39, 0x33, 0x94, 0xef, 0x33, 0x43, 0x39, 0x29,
	0xde, 0xe5, 0xcb, 0x59, 0xfe, 0x3b, 0x32, 0xee, 0x13, 0xd1, 0xc9, 0x26, 0xfb, 0x7e, 0xf1, 0x27,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0x54, 0xd5, 0x0a, 0x5b, 0x03, 0x00, 0x00,
}

func (m *CommandMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommandMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommandMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Signature != nil {
		{
			size, err := m.Signature.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCommand(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.KeyID) > 0 {
		i -= len(m.KeyID)
		copy(dAtA[i:], m.KeyID)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.KeyID)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Status != 0 {
		i = encodeVarintCommand(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.SigHash.Size()
		i -= size
		if _, err := m.SigHash.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCommand(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintCommand(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommand(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommand(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CommandMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	l = m.SigHash.Size()
	n += 1 + l + sovCommand(uint64(l))
	if m.Status != 0 {
		n += 1 + sovCommand(uint64(m.Status))
	}
	l = len(m.KeyID)
	if l > 0 {
		n += 1 + l + sovCommand(uint64(l))
	}
	if m.Signature != nil {
		l = m.Signature.Size()
		n += 1 + l + sovCommand(uint64(l))
	}
	return n
}

func sovCommand(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommand(x uint64) (n int) {
	return sovCommand(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CommandMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommandMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommandMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = append(m.ID[:0], dAtA[iNdEx:postIndex]...)
			if m.ID == nil {
				m.ID = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SigHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CommandStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyID = github_com_scalarorg_scalar_core_x_multisig_exported.KeyID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCommand
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCommand
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Signature == nil {
				m.Signature = &types.Any{}
			}
			if err := m.Signature.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommand(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommand
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommand(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommand
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommand
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommand
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommand
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommand
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommand        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommand          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommand = fmt.Errorf("proto: unexpected end of group")
)
