// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scalar/covenant/v1beta1/events.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SigningStarted struct {
	Module           string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	SigID            uint64 `protobuf:"varint,2,opt,name=sig_id,json=sigId,proto3" json:"sig_id,omitempty"`
	Psbt             []byte `protobuf:"bytes,3,opt,name=psbt,proto3" json:"psbt,omitempty"`
	RequestingModule string `protobuf:"bytes,4,opt,name=requesting_module,json=requestingModule,proto3" json:"requesting_module,omitempty"`
}

func (m *SigningStarted) Reset()         { *m = SigningStarted{} }
func (m *SigningStarted) String() string { return proto.CompactTextString(m) }
func (*SigningStarted) ProtoMessage()    {}
func (*SigningStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_1539e454966a6a42, []int{0}
}
func (m *SigningStarted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigningStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SigningStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningStarted.Merge(m, src)
}
func (m *SigningStarted) XXX_Size() int {
	return m.Size()
}
func (m *SigningStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningStarted.DiscardUnknown(m)
}

var xxx_messageInfo_SigningStarted proto.InternalMessageInfo

func (m *SigningStarted) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *SigningStarted) GetSigID() uint64 {
	if m != nil {
		return m.SigID
	}
	return 0
}

func (m *SigningStarted) GetPsbt() []byte {
	if m != nil {
		return m.Psbt
	}
	return nil
}

func (m *SigningStarted) GetRequestingModule() string {
	if m != nil {
		return m.RequestingModule
	}
	return ""
}

type SigningCompleted struct {
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	SigID  uint64 `protobuf:"varint,2,opt,name=sig_id,json=sigId,proto3" json:"sig_id,omitempty"`
}

func (m *SigningCompleted) Reset()         { *m = SigningCompleted{} }
func (m *SigningCompleted) String() string { return proto.CompactTextString(m) }
func (*SigningCompleted) ProtoMessage()    {}
func (*SigningCompleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_1539e454966a6a42, []int{1}
}
func (m *SigningCompleted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigningCompleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigningCompleted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigningCompleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningCompleted.Merge(m, src)
}
func (m *SigningCompleted) XXX_Size() int {
	return m.Size()
}
func (m *SigningCompleted) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningCompleted.DiscardUnknown(m)
}

var xxx_messageInfo_SigningCompleted proto.InternalMessageInfo

func (m *SigningCompleted) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *SigningCompleted) GetSigID() uint64 {
	if m != nil {
		return m.SigID
	}
	return 0
}

type SigningExpired struct {
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	SigID  uint64 `protobuf:"varint,2,opt,name=sig_id,json=sigId,proto3" json:"sig_id,omitempty"`
}

func (m *SigningExpired) Reset()         { *m = SigningExpired{} }
func (m *SigningExpired) String() string { return proto.CompactTextString(m) }
func (*SigningExpired) ProtoMessage()    {}
func (*SigningExpired) Descriptor() ([]byte, []int) {
	return fileDescriptor_1539e454966a6a42, []int{2}
}
func (m *SigningExpired) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigningExpired) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigningExpired.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigningExpired) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningExpired.Merge(m, src)
}
func (m *SigningExpired) XXX_Size() int {
	return m.Size()
}
func (m *SigningExpired) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningExpired.DiscardUnknown(m)
}

var xxx_messageInfo_SigningExpired proto.InternalMessageInfo

func (m *SigningExpired) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *SigningExpired) GetSigID() uint64 {
	if m != nil {
		return m.SigID
	}
	return 0
}

type TapScriptSigSubmitted struct {
	Module       string                                        `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	SigID        uint64                                        `protobuf:"varint,2,opt,name=sig_id,json=sigId,proto3" json:"sig_id,omitempty"`
	Participant  github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,3,opt,name=participant,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"participant,omitempty"`
	TapScriptSig TapScriptSig                                  `protobuf:"bytes,4,opt,name=tap_script_sig,json=tapScriptSig,proto3,casttype=TapScriptSig" json:"tap_script_sig,omitempty"`
}

func (m *TapScriptSigSubmitted) Reset()         { *m = TapScriptSigSubmitted{} }
func (m *TapScriptSigSubmitted) String() string { return proto.CompactTextString(m) }
func (*TapScriptSigSubmitted) ProtoMessage()    {}
func (*TapScriptSigSubmitted) Descriptor() ([]byte, []int) {
	return fileDescriptor_1539e454966a6a42, []int{3}
}
func (m *TapScriptSigSubmitted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TapScriptSigSubmitted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TapScriptSigSubmitted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TapScriptSigSubmitted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TapScriptSigSubmitted.Merge(m, src)
}
func (m *TapScriptSigSubmitted) XXX_Size() int {
	return m.Size()
}
func (m *TapScriptSigSubmitted) XXX_DiscardUnknown() {
	xxx_messageInfo_TapScriptSigSubmitted.DiscardUnknown(m)
}

var xxx_messageInfo_TapScriptSigSubmitted proto.InternalMessageInfo

func (m *TapScriptSigSubmitted) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *TapScriptSigSubmitted) GetSigID() uint64 {
	if m != nil {
		return m.SigID
	}
	return 0
}

func (m *TapScriptSigSubmitted) GetParticipant() github_com_cosmos_cosmos_sdk_types.ValAddress {
	if m != nil {
		return m.Participant
	}
	return nil
}

func (m *TapScriptSigSubmitted) GetTapScriptSig() TapScriptSig {
	if m != nil {
		return m.TapScriptSig
	}
	return nil
}

func init() {
	proto.RegisterType((*SigningStarted)(nil), "scalar.covenant.v1beta1.SigningStarted")
	proto.RegisterType((*SigningCompleted)(nil), "scalar.covenant.v1beta1.SigningCompleted")
	proto.RegisterType((*SigningExpired)(nil), "scalar.covenant.v1beta1.SigningExpired")
	proto.RegisterType((*TapScriptSigSubmitted)(nil), "scalar.covenant.v1beta1.TapScriptSigSubmitted")
}

func init() {
	proto.RegisterFile("scalar/covenant/v1beta1/events.proto", fileDescriptor_1539e454966a6a42)
}

var fileDescriptor_1539e454966a6a42 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x3f, 0x8b, 0xdb, 0x30,
	0x1c, 0x8d, 0x5a, 0x27, 0x10, 0xd5, 0x84, 0xd4, 0xf4, 0x4f, 0xe8, 0x60, 0x9b, 0xd0, 0x21, 0x50,
	0x62, 0x63, 0x0a, 0x1d, 0xba, 0xd5, 0x6d, 0x87, 0xf4, 0xcf, 0x62, 0x97, 0x0e, 0x5d, 0x8c, 0x6c,
	0x0b, 0x55, 0xd4, 0xb6, 0x54, 0x49, 0x0e, 0xb9, 0x6f, 0x71, 0xb7, 0xdd, 0x7a, 0xdf, 0xe6, 0xc6,
	0x8c, 0x37, 0x99, 0xc3, 0xf9, 0x16, 0x99, 0x8e, 0x53, 0x7c, 0x17, 0xef, 0x99, 0xf4, 0x7e, 0xfa,
	0x3d, 0x1e, 0xef, 0xf7, 0x78, 0xf0, 0xad, 0xcc, 0x50, 0x81, 0x84, 0x9f, 0xb1, 0x35, 0xae, 0x50,
	0xa5, 0xfc, 0x75, 0x90, 0x62, 0x85, 0x02, 0x1f, 0xaf, 0x71, 0xa5, 0xa4, 0xc7, 0x05, 0x53, 0xcc,
	0x7a, 0x7d, 0x60, 0x79, 0x0f, 0x2c, 0xaf, 0x63, 0xbd, 0x79, 0x41, 0x18, 0x61, 0x9a, 0xe3, 0xdf,
	0xa3, 0x03, 0x7d, 0x7e, 0x01, 0xe0, 0x24, 0xa6, 0xa4, 0xa2, 0x15, 0x89, 0x15, 0x12, 0x0a, 0xe7,
	0xd6, 0x2b, 0x38, 0x2a, 0x59, 0x5e, 0x17, 0x78, 0x06, 0x5c, 0xb0, 0x18, 0x47, 0xdd, 0x64, 0xb9,
	0x70, 0x24, 0x29, 0x49, 0x68, 0x3e, 0x7b, 0xe2, 0x82, 0x85, 0x11, 0x8e, 0xdb, 0xc6, 0x19, 0xc6,
	0x94, 0xac, 0xbe, 0x44, 0x43, 0x49, 0xc9, 0x2a, 0xb7, 0x2c, 0x68, 0x70, 0x99, 0xaa, 0xd9, 0x53,
	0x17, 0x2c, 0xcc, 0x48, 0x63, 0xeb, 0x1d, 0x7c, 0x2e, 0xf0, 0xff, 0x1a, 0x4b, 0x45, 0x2b, 0x92,
	0x74, 0xc2, 0x86, 0x16, 0x9e, 0x1e, 0x17, 0x3f, 0xf5, 0xff, 0x47, 0xe3, 0xf2, 0xca, 0x01, 0xf3,
	0x1f, 0x70, 0xda, 0x59, 0xfa, 0xcc, 0x4a, 0x5e, 0xe0, 0x93, 0x4c, 0xcd, 0xbf, 0x3d, 0x1e, 0xf8,
	0x75, 0xc3, 0xa9, 0x38, 0x49, 0xab, 0x01, 0xf0, 0xe5, 0x2f, 0xc4, 0xe3, 0x4c, 0x50, 0xae, 0x62,
	0x4a, 0xe2, 0x3a, 0x2d, 0xa9, 0x3a, 0x2d, 0xb4, 0x18, 0x3e, 0xe3, 0x48, 0x28, 0x9a, 0x51, 0x8e,
	0xaa, 0x2e, 0xbb, 0x30, 0xd8, 0x37, 0xce, 0x92, 0x50, 0xf5, 0xb7, 0x4e, 0xbd, 0x8c, 0x95, 0x7e,
	0xc6, 0x64, 0xc9, 0x64, 0xf7, 0x2c, 0x65, 0xfe, 0xcf, 0x57, 0x67, 0x1c, 0x4b, 0xef, 0x37, 0x2a,
	0x3e, 0xe5, 0xb9, 0xc0, 0x52, 0x46, 0x7d, 0x15, 0xeb, 0x03, 0x9c, 0x28, 0xc4, 0x13, 0xa9, 0x8d,
	0x26, 0x92, 0x12, 0x1d, 0xb9, 0x19, 0x4e, 0xf7, 0x8d, 0x63, 0xf6, 0x2f, 0x88, 0x4c, 0xd5, 0x9b,
	0xc2, 0xef, 0xd7, 0xad, 0x0d, 0xb6, 0xad, 0x0d, 0x6e, 0x5b, 0x1b, 0x9c, 0xef, 0xec, 0xc1, 0x76,
	0x67, 0x0f, 0x6e, 0x76, 0xf6, 0xe0, 0x4f, 0xd0, 0x73, 0x73, 0xa8, 0x18, 0x13, 0xa4, 0x43, 0xcb,
	0x8c, 0x09, 0xec, 0x6f, 0x8e, 0xcd, 0xd4, 0xe6, 0xd2, 0x91, 0xae, 0xd8, 0xfb, 0xbb, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x91, 0x78, 0xd6, 0xa1, 0xb9, 0x02, 0x00, 0x00,
}

func (m *SigningStarted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigningStarted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigningStarted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestingModule) > 0 {
		i -= len(m.RequestingModule)
		copy(dAtA[i:], m.RequestingModule)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RequestingModule)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Psbt) > 0 {
		i -= len(m.Psbt)
		copy(dAtA[i:], m.Psbt)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Psbt)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SigID != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.SigID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SigningCompleted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigningCompleted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigningCompleted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SigID != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.SigID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SigningExpired) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigningExpired) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigningExpired) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SigID != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.SigID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TapScriptSigSubmitted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TapScriptSigSubmitted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TapScriptSigSubmitted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TapScriptSig) > 0 {
		i -= len(m.TapScriptSig)
		copy(dAtA[i:], m.TapScriptSig)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.TapScriptSig)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SigID != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.SigID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SigningStarted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.SigID != 0 {
		n += 1 + sovEvents(uint64(m.SigID))
	}
	l = len(m.Psbt)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.RequestingModule)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *SigningCompleted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.SigID != 0 {
		n += 1 + sovEvents(uint64(m.SigID))
	}
	return n
}

func (m *SigningExpired) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.SigID != 0 {
		n += 1 + sovEvents(uint64(m.SigID))
	}
	return n
}

func (m *TapScriptSigSubmitted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.SigID != 0 {
		n += 1 + sovEvents(uint64(m.SigID))
	}
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.TapScriptSig)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SigningStarted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigningStarted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigningStarted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigID", wireType)
			}
			m.SigID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SigID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Psbt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Psbt = append(m.Psbt[:0], dAtA[iNdEx:postIndex]...)
			if m.Psbt == nil {
				m.Psbt = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestingModule", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestingModule = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigningCompleted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigningCompleted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigningCompleted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigID", wireType)
			}
			m.SigID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SigID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigningExpired) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigningExpired: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigningExpired: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigID", wireType)
			}
			m.SigID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SigID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TapScriptSigSubmitted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TapScriptSigSubmitted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TapScriptSigSubmitted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigID", wireType)
			}
			m.SigID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SigID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = append(m.Participant[:0], dAtA[iNdEx:postIndex]...)
			if m.Participant == nil {
				m.Participant = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TapScriptSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TapScriptSig = append(m.TapScriptSig[:0], dAtA[iNdEx:postIndex]...)
			if m.TapScriptSig == nil {
				m.TapScriptSig = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
