// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scalar/covenant/v1beta1/types.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	_ "github.com/regen-network/cosmos-proto"
	utils "github.com/scalarorg/scalar-core/utils"
	exported "github.com/scalarorg/scalar-core/x/covenant/exported"
	github_com_scalarorg_scalar_core_x_multisig_exported "github.com/scalarorg/scalar-core/x/multisig/exported"
	exported1 "github.com/scalarorg/scalar-core/x/snapshot/exported"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Unspecified Status = 0
	Activated   Status = 1
	Deactivated Status = 2
)

var Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_ACTIVATED",
	2: "STATUS_DEACTIVATED",
}

var Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_ACTIVATED":   1,
	"STATUS_DEACTIVATED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_404fd62bcdc2fd38, []int{0}
}

// Custodian represents an individual custodian configuration
type Custodian struct {
	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BtcPubkey []byte `protobuf:"bytes,2,opt,name=btc_pubkey,json=btcPubkey,proto3" json:"btc_pubkey,omitempty"`
	// "0215da913b3e87b4932b1e1b87d9667c28e7250aa0ed60b3a31095f541e1641488"
	Status      Status `protobuf:"varint,3,opt,name=status,proto3,enum=scalar.covenant.v1beta1.Status" json:"status,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *Custodian) Reset()         { *m = Custodian{} }
func (m *Custodian) String() string { return proto.CompactTextString(m) }
func (*Custodian) ProtoMessage()    {}
func (*Custodian) Descriptor() ([]byte, []int) {
	return fileDescriptor_404fd62bcdc2fd38, []int{0}
}
func (m *Custodian) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Custodian) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Custodian.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Custodian) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Custodian.Merge(m, src)
}
func (m *Custodian) XXX_Size() int {
	return m.Size()
}
func (m *Custodian) XXX_DiscardUnknown() {
	xxx_messageInfo_Custodian.DiscardUnknown(m)
}

var xxx_messageInfo_Custodian proto.InternalMessageInfo

func (m *Custodian) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Custodian) GetBtcPubkey() []byte {
	if m != nil {
		return m.BtcPubkey
	}
	return nil
}

func (m *Custodian) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Unspecified
}

func (m *Custodian) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// CustodianGroup represents a group of custodians with their configuration
// uid is used as identity of the group, btc_pubkey is change by list of
// custodians
type CustodianGroup struct {
	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BtcPubkey string `protobuf:"bytes,3,opt,name=btc_pubkey,json=btcPubkey,proto3" json:"btc_pubkey,omitempty"`
	// "tb1p07q440mdl4uyywns325dk8pvjphwety3psp4zvkngtjf3z3hhr2sfar3hv"
	Quorum      uint32       `protobuf:"varint,4,opt,name=quorum,proto3" json:"quorum,omitempty"`
	Status      Status       `protobuf:"varint,5,opt,name=status,proto3,enum=scalar.covenant.v1beta1.Status" json:"status,omitempty"`
	Description string       `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Custodians  []*Custodian `protobuf:"bytes,7,rep,name=custodians,proto3" json:"custodians,omitempty"`
}

func (m *CustodianGroup) Reset()         { *m = CustodianGroup{} }
func (m *CustodianGroup) String() string { return proto.CompactTextString(m) }
func (*CustodianGroup) ProtoMessage()    {}
func (*CustodianGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_404fd62bcdc2fd38, []int{1}
}
func (m *CustodianGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustodianGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustodianGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustodianGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodianGroup.Merge(m, src)
}
func (m *CustodianGroup) XXX_Size() int {
	return m.Size()
}
func (m *CustodianGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodianGroup.DiscardUnknown(m)
}

var xxx_messageInfo_CustodianGroup proto.InternalMessageInfo

func (m *CustodianGroup) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CustodianGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustodianGroup) GetBtcPubkey() string {
	if m != nil {
		return m.BtcPubkey
	}
	return ""
}

func (m *CustodianGroup) GetQuorum() uint32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *CustodianGroup) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Unspecified
}

func (m *CustodianGroup) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CustodianGroup) GetCustodians() []*Custodian {
	if m != nil {
		return m.Custodians
	}
	return nil
}

type PsbtMultiSig struct {
	KeyID         github_com_scalarorg_scalar_core_x_multisig_exported.KeyID `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3,casttype=github.com/scalarorg/scalar-core/x/multisig/exported.KeyID" json:"key_id,omitempty"`
	Psbt          Psbt                                                       `protobuf:"bytes,2,opt,name=psbt,proto3,casttype=Psbt" json:"psbt,omitempty"`
	TapScriptSigs map[string]*exported.TapScriptSig                          `protobuf:"bytes,3,rep,name=tap_script_sigs,json=tapScriptSigs,proto3" json:"tap_script_sigs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *PsbtMultiSig) Reset()         { *m = PsbtMultiSig{} }
func (m *PsbtMultiSig) String() string { return proto.CompactTextString(m) }
func (*PsbtMultiSig) ProtoMessage()    {}
func (*PsbtMultiSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_404fd62bcdc2fd38, []int{2}
}
func (m *PsbtMultiSig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PsbtMultiSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PsbtMultiSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PsbtMultiSig.Merge(m, src)
}
func (m *PsbtMultiSig) XXX_Size() int {
	return m.Size()
}
func (m *PsbtMultiSig) XXX_DiscardUnknown() {
	xxx_messageInfo_PsbtMultiSig.DiscardUnknown(m)
}

var xxx_messageInfo_PsbtMultiSig proto.InternalMessageInfo

func (m *PsbtMultiSig) GetKeyID() github_com_scalarorg_scalar_core_x_multisig_exported.KeyID {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *PsbtMultiSig) GetPsbt() Psbt {
	if m != nil {
		return m.Psbt
	}
	return nil
}

func (m *PsbtMultiSig) GetTapScriptSigs() map[string]*exported.TapScriptSig {
	if m != nil {
		return m.TapScriptSigs
	}
	return nil
}

type Key struct {
	ID               github_com_scalarorg_scalar_core_x_multisig_exported.KeyID                `protobuf:"bytes,1,opt,name=id,proto3,casttype=github.com/scalarorg/scalar-core/x/multisig/exported.KeyID" json:"id,omitempty"`
	Snapshot         exported1.Snapshot                                                        `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot"`
	PubKeys          map[string]github_com_scalarorg_scalar_core_x_multisig_exported.PublicKey `protobuf:"bytes,3,rep,name=pub_keys,json=pubKeys,proto3,castvalue=github.com/scalarorg/scalar-core/x/multisig/exported.PublicKey" json:"pub_keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SigningThreshold utils.Threshold                                                           `protobuf:"bytes,4,opt,name=signing_threshold,json=signingThreshold,proto3" json:"signing_threshold"`
	State            exported.KeyState                                                         `protobuf:"varint,5,opt,name=state,proto3,enum=scalar.covenant.exported.v1beta1.KeyState" json:"state,omitempty"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_404fd62bcdc2fd38, []int{3}
}
func (m *Key) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return m.Size()
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetID() github_com_scalarorg_scalar_core_x_multisig_exported.KeyID {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Key) GetSnapshot() exported1.Snapshot {
	if m != nil {
		return m.Snapshot
	}
	return exported1.Snapshot{}
}

func (m *Key) GetPubKeys() map[string]github_com_scalarorg_scalar_core_x_multisig_exported.PublicKey {
	if m != nil {
		return m.PubKeys
	}
	return nil
}

func (m *Key) GetSigningThreshold() utils.Threshold {
	if m != nil {
		return m.SigningThreshold
	}
	return utils.Threshold{}
}

func (m *Key) GetState() exported.KeyState {
	if m != nil {
		return m.State
	}
	return exported.Inactive
}

type SigningSession struct {
	ID             uint64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PsbtMultiSig   PsbtMultiSig       `protobuf:"bytes,2,opt,name=psbt_multi_sig,json=psbtMultiSig,proto3" json:"psbt_multi_sig"`
	State          exported.PsbtState `protobuf:"varint,3,opt,name=state,proto3,enum=scalar.covenant.exported.v1beta1.PsbtState" json:"state,omitempty"`
	Key            Key                `protobuf:"bytes,4,opt,name=key,proto3" json:"key"`
	Psbt           Psbt               `protobuf:"bytes,5,opt,name=psbt,proto3,casttype=Psbt" json:"psbt,omitempty"`
	ExpiresAt      int64              `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CompletedAt    int64              `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	GracePeriod    int64              `protobuf:"varint,8,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	Module         string             `protobuf:"bytes,9,opt,name=module,proto3" json:"module,omitempty"`
	ModuleMetadata *types.Any         `protobuf:"bytes,10,opt,name=module_metadata,json=moduleMetadata,proto3" json:"module_metadata,omitempty"`
}

func (m *SigningSession) Reset()         { *m = SigningSession{} }
func (m *SigningSession) String() string { return proto.CompactTextString(m) }
func (*SigningSession) ProtoMessage()    {}
func (*SigningSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_404fd62bcdc2fd38, []int{4}
}
func (m *SigningSession) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigningSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SigningSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningSession.Merge(m, src)
}
func (m *SigningSession) XXX_Size() int {
	return m.Size()
}
func (m *SigningSession) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningSession.DiscardUnknown(m)
}

var xxx_messageInfo_SigningSession proto.InternalMessageInfo

func (m *SigningSession) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SigningSession) GetPsbtMultiSig() PsbtMultiSig {
	if m != nil {
		return m.PsbtMultiSig
	}
	return PsbtMultiSig{}
}

func (m *SigningSession) GetState() exported.PsbtState {
	if m != nil {
		return m.State
	}
	return exported.NonExistent
}

func (m *SigningSession) GetKey() Key {
	if m != nil {
		return m.Key
	}
	return Key{}
}

func (m *SigningSession) GetPsbt() Psbt {
	if m != nil {
		return m.Psbt
	}
	return nil
}

func (m *SigningSession) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *SigningSession) GetCompletedAt() int64 {
	if m != nil {
		return m.CompletedAt
	}
	return 0
}

func (m *SigningSession) GetGracePeriod() int64 {
	if m != nil {
		return m.GracePeriod
	}
	return 0
}

func (m *SigningSession) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *SigningSession) GetModuleMetadata() *types.Any {
	if m != nil {
		return m.ModuleMetadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("scalar.covenant.v1beta1.Status", Status_name, Status_value)
	proto.RegisterType((*Custodian)(nil), "scalar.covenant.v1beta1.Custodian")
	proto.RegisterType((*CustodianGroup)(nil), "scalar.covenant.v1beta1.CustodianGroup")
	proto.RegisterType((*PsbtMultiSig)(nil), "scalar.covenant.v1beta1.PsbtMultiSig")
	proto.RegisterMapType((map[string]*exported.TapScriptSig)(nil), "scalar.covenant.v1beta1.PsbtMultiSig.TapScriptSigsEntry")
	proto.RegisterType((*Key)(nil), "scalar.covenant.v1beta1.Key")
	proto.RegisterMapType((map[string]github_com_scalarorg_scalar_core_x_multisig_exported.PublicKey)(nil), "scalar.covenant.v1beta1.Key.PubKeysEntry")
	proto.RegisterType((*SigningSession)(nil), "scalar.covenant.v1beta1.SigningSession")
}

func init() {
	proto.RegisterFile("scalar/covenant/v1beta1/types.proto", fileDescriptor_404fd62bcdc2fd38)
}

var fileDescriptor_404fd62bcdc2fd38 = []byte{
	// 1036 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0x8e, 0xf3, 0xd5, 0x66, 0x92, 0x7e, 0x30, 0xaa, 0x96, 0x6c, 0xb4, 0x9b, 0x84, 0x2e, 0x1f,
	0xa5, 0xb0, 0xb6, 0x5a, 0x90, 0x58, 0xf5, 0x80, 0x48, 0x9a, 0xb2, 0xaa, 0x42, 0x51, 0x70, 0x52,
	0x0e, 0x1c, 0x30, 0x63, 0x7b, 0xd6, 0x1d, 0x35, 0xf1, 0x18, 0xcf, 0xb8, 0xaa, 0x6f, 0x5c, 0x90,
	0x56, 0xd5, 0x1e, 0x38, 0xc2, 0x61, 0x0f, 0x88, 0xbf, 0xc0, 0x8f, 0x58, 0x71, 0xda, 0x23, 0xa7,
	0x82, 0x5a, 0x89, 0x1f, 0xb1, 0x27, 0xe4, 0x99, 0xb1, 0x6b, 0xd1, 0x96, 0xae, 0x76, 0x6f, 0xe3,
	0xd7, 0xcf, 0xbc, 0xf3, 0x3e, 0xcf, 0xfb, 0x3e, 0x63, 0x83, 0x7b, 0xcc, 0x41, 0x53, 0x14, 0x1a,
	0x0e, 0x3d, 0xc2, 0x3e, 0xf2, 0xb9, 0x71, 0xb4, 0x61, 0x63, 0x8e, 0x36, 0x0c, 0x1e, 0x07, 0x98,
	0xe9, 0x41, 0x48, 0x39, 0x85, 0x6f, 0x4a, 0x90, 0x9e, 0x82, 0x74, 0x05, 0x6a, 0xdd, 0xf6, 0x28,
	0xf5, 0xa6, 0xd8, 0x10, 0x30, 0x3b, 0x7a, 0x64, 0x20, 0x3f, 0x96, 0x7b, 0x5a, 0x2b, 0x1e, 0xf5,
	0xa8, 0x58, 0x1a, 0xc9, 0x4a, 0x45, 0x6f, 0x3b, 0x94, 0xcd, 0x28, 0xb3, 0xe4, 0x0b, 0xf9, 0xa0,
	0x5e, 0x7d, 0xf8, 0xdf, 0x4a, 0xf0, 0x71, 0x40, 0x43, 0x8e, 0xdd, 0xab, 0x4a, 0xca, 0xd0, 0xcc,
	0x47, 0x01, 0x3b, 0xa0, 0x37, 0xa0, 0xdf, 0x56, 0xe8, 0x88, 0x93, 0x29, 0xbb, 0x40, 0x1c, 0x84,
	0x98, 0x1d, 0xd0, 0xa9, 0x2b, 0x51, 0xab, 0xbf, 0x68, 0xa0, 0xb6, 0x1d, 0x31, 0x4e, 0x5d, 0x82,
	0x7c, 0x08, 0x41, 0xd9, 0x47, 0x33, 0xdc, 0xd4, 0xba, 0xda, 0x5a, 0xcd, 0x14, 0x6b, 0x78, 0x17,
	0x00, 0x9b, 0x3b, 0x56, 0x10, 0xd9, 0x87, 0x38, 0x6e, 0x16, 0xbb, 0xda, 0x5a, 0xc3, 0xac, 0xd9,
	0xdc, 0x19, 0x89, 0x00, 0xfc, 0x04, 0x54, 0x19, 0x47, 0x3c, 0x62, 0xcd, 0x52, 0x57, 0x5b, 0x5b,
	0xdc, 0xec, 0xe8, 0xd7, 0x08, 0xa7, 0x8f, 0x05, 0xcc, 0x54, 0x70, 0xd8, 0x05, 0x75, 0x17, 0x33,
	0x27, 0x24, 0x01, 0x27, 0xd4, 0x6f, 0x96, 0xc5, 0x91, 0xf9, 0xd0, 0xea, 0x93, 0x22, 0x58, 0xcc,
	0x6a, 0x7b, 0x18, 0xd2, 0x28, 0x80, 0xcb, 0xa0, 0x14, 0x11, 0x57, 0xd5, 0x97, 0x2c, 0xb3, 0x92,
	0x8b, 0xd7, 0x96, 0x5c, 0x12, 0x6f, 0x72, 0x25, 0xdf, 0x02, 0xd5, 0xef, 0x23, 0x1a, 0x46, 0x33,
	0x71, 0xe8, 0x82, 0xa9, 0x9e, 0x72, 0x54, 0x2a, 0xaf, 0x45, 0xa5, 0x7a, 0x89, 0x0a, 0xec, 0x03,
	0xe0, 0xa4, 0x4c, 0x58, 0x73, 0xae, 0x5b, 0x5a, 0xab, 0x6f, 0xae, 0x5e, 0x9b, 0x3e, 0x23, 0x6d,
	0xe6, 0x76, 0xad, 0xfe, 0x53, 0x04, 0x8d, 0x11, 0xb3, 0xf9, 0x5e, 0x34, 0xe5, 0x64, 0x4c, 0x3c,
	0xf8, 0x2d, 0xa8, 0x1e, 0xe2, 0xd8, 0x4a, 0xf5, 0xe8, 0x3f, 0x3c, 0x3b, 0xed, 0x54, 0x86, 0x38,
	0xde, 0x1d, 0xbc, 0x38, 0xed, 0x6c, 0x79, 0x84, 0x1f, 0x44, 0xb6, 0xee, 0xd0, 0x99, 0x21, 0xcf,
	0xa1, 0xa1, 0xa7, 0x56, 0xf7, 0x1d, 0x1a, 0x62, 0xe3, 0xd8, 0x98, 0x25, 0x99, 0x18, 0xf1, 0xb2,
	0x41, 0xd2, 0xc5, 0x6e, 0xb3, 0x72, 0x88, 0xe3, 0x5d, 0x17, 0xde, 0x01, 0xe5, 0x80, 0xd9, 0x5c,
	0xf6, 0xbc, 0x3f, 0xff, 0xe2, 0xb4, 0x53, 0x4e, 0xce, 0x37, 0x45, 0x14, 0x7e, 0x07, 0x96, 0x38,
	0x0a, 0x2c, 0xc9, 0xd1, 0x62, 0xc4, 0x4b, 0x26, 0x20, 0xe1, 0xf5, 0xe0, 0x5a, 0x5e, 0xf9, 0xea,
	0xf5, 0x09, 0x0a, 0xc6, 0x62, 0xef, 0x98, 0x78, 0x6c, 0xc7, 0xe7, 0x61, 0x6c, 0x2e, 0xf0, 0x7c,
	0xac, 0x15, 0x00, 0x78, 0x19, 0x94, 0x8c, 0x40, 0xd2, 0x55, 0x35, 0x02, 0x49, 0x3f, 0x07, 0xa0,
	0x72, 0x84, 0xa6, 0x91, 0x9c, 0x81, 0xfa, 0xa6, 0x7e, 0xe9, 0xfc, 0x8c, 0x5e, 0x5a, 0x48, 0x3e,
	0xad, 0x29, 0x37, 0x6f, 0x15, 0x1f, 0x68, 0x5b, 0xe5, 0x9f, 0x7f, 0xed, 0x68, 0xab, 0x4f, 0xca,
	0xa0, 0x34, 0xc4, 0x31, 0x9c, 0x80, 0x62, 0xa6, 0xed, 0xe0, 0xec, 0xb4, 0x53, 0x7c, 0x6d, 0x61,
	0x8b, 0xc4, 0x85, 0x5f, 0x80, 0xf9, 0xd4, 0xc0, 0xaa, 0xe0, 0xf5, 0xb4, 0xe0, 0x34, 0x7e, 0xb9,
	0xe0, 0xb1, 0x7a, 0xd3, 0x2f, 0x3f, 0x3b, 0xed, 0x14, 0xcc, 0x2c, 0x03, 0x7c, 0xac, 0x81, 0xf9,
	0x20, 0xb2, 0xad, 0x43, 0x1c, 0xa7, 0xfa, 0xbf, 0x7f, 0xad, 0xfe, 0x43, 0x1c, 0xeb, 0xa3, 0xc8,
	0x1e, 0xe2, 0x58, 0x6a, 0xd9, 0xef, 0x9f, 0xfc, 0xd5, 0xf9, 0xf4, 0x95, 0xf8, 0x8c, 0x22, 0x7b,
	0x4a, 0x9c, 0x21, 0x8e, 0xcd, 0xb9, 0x40, 0x66, 0x84, 0x26, 0x78, 0x83, 0x11, 0xcf, 0x27, 0xbe,
	0x67, 0x65, 0xb7, 0x8c, 0x70, 0x58, 0xfd, 0xc2, 0x49, 0xe2, 0x32, 0xba, 0x68, 0x43, 0x0a, 0x53,
	0xb4, 0x96, 0xd5, 0xfe, 0x2c, 0x0e, 0x3f, 0x03, 0x95, 0xc4, 0x63, 0x58, 0x39, 0x72, 0xfd, 0xe6,
	0xd6, 0x0e, 0x71, 0x9c, 0xb8, 0x13, 0x9b, 0x72, 0x63, 0x6b, 0x0b, 0x34, 0xf2, 0x94, 0xaf, 0x18,
	0x9f, 0x95, 0xfc, 0xf8, 0x34, 0x2e, 0x8f, 0xc3, 0x0f, 0x65, 0xb0, 0x38, 0x96, 0x85, 0x8d, 0x31,
	0x63, 0x89, 0x9d, 0x6f, 0x65, 0x93, 0x51, 0xee, 0x57, 0xe5, 0x64, 0x88, 0xde, 0x7e, 0x05, 0x16,
	0x13, 0x6f, 0x58, 0x42, 0xaf, 0xc4, 0x13, 0xaa, 0xc3, 0xef, 0xbc, 0x94, 0x25, 0x94, 0x0a, 0x8d,
	0x20, 0x6f, 0xf2, 0x5e, 0xaa, 0x80, 0xbc, 0x5e, 0x3f, 0xb8, 0x59, 0x81, 0x24, 0x65, 0x5e, 0x02,
	0xf8, 0xb1, 0xa4, 0x2c, 0x5b, 0x71, 0xe7, 0xff, 0xa6, 0x43, 0x55, 0x20, 0x64, 0x49, 0xdd, 0x5f,
	0xb9, 0xd2, 0xfd, 0x77, 0x01, 0xc0, 0xc7, 0x01, 0x09, 0x31, 0xb3, 0x10, 0x17, 0x37, 0x5e, 0xc9,
	0xac, 0xa9, 0x48, 0x8f, 0xc3, 0xb7, 0x40, 0xc3, 0xa1, 0xb3, 0x60, 0x8a, 0x39, 0x76, 0x13, 0xc0,
	0x9c, 0x00, 0xd4, 0xb3, 0x98, 0x84, 0x78, 0x21, 0x72, 0xb0, 0x15, 0xe0, 0x90, 0x50, 0xb7, 0x39,
	0x2f, 0x21, 0x22, 0x36, 0x12, 0xa1, 0xe4, 0xa2, 0x9e, 0x51, 0x37, 0x9a, 0xe2, 0x66, 0x4d, 0xb4,
	0x4b, 0x3d, 0x41, 0x02, 0x96, 0xe4, 0xca, 0x9a, 0x61, 0x8e, 0x5c, 0xc4, 0x51, 0x13, 0x08, 0x72,
	0x2b, 0xba, 0xfc, 0x38, 0xeb, 0xe9, 0xc7, 0x59, 0xef, 0xf9, 0x71, 0x7f, 0xfd, 0x8f, 0xdf, 0xef,
	0xbf, 0x9b, 0x9b, 0x72, 0xf9, 0x09, 0x36, 0x1c, 0xea, 0x62, 0xc7, 0x18, 0x25, 0xc8, 0x3d, 0x14,
	0xb2, 0x03, 0x34, 0xc5, 0xa1, 0xb9, 0x28, 0x13, 0xef, 0xa9, 0xbc, 0x72, 0x04, 0xd6, 0x7f, 0xd4,
	0x40, 0x55, 0xde, 0xf9, 0xf0, 0x3d, 0x00, 0xc7, 0x93, 0xde, 0x64, 0x7f, 0x6c, 0xed, 0x7f, 0x39,
	0x1e, 0xed, 0x6c, 0xef, 0x7e, 0xbe, 0xbb, 0x33, 0x58, 0x2e, 0xb4, 0x96, 0x4e, 0x9e, 0x76, 0xeb,
	0xfb, 0x3e, 0x0b, 0xb0, 0x43, 0x1e, 0x11, 0xec, 0xc2, 0x7b, 0x60, 0x59, 0x01, 0x7b, 0xdb, 0x93,
	0xdd, 0xaf, 0x7b, 0x93, 0x9d, 0xc1, 0xb2, 0xd6, 0x5a, 0x38, 0x79, 0xda, 0xad, 0xf5, 0x1c, 0x4e,
	0x8e, 0x10, 0xc7, 0x6e, 0x2e, 0xdb, 0x60, 0xe7, 0x02, 0x56, 0x94, 0xd9, 0x06, 0x18, 0xa5, 0xc0,
	0x56, 0xf9, 0xf1, 0x6f, 0xed, 0x42, 0x7f, 0xf8, 0xec, 0xac, 0xad, 0x3d, 0x3f, 0x6b, 0x6b, 0x7f,
	0x9f, 0xb5, 0xb5, 0x9f, 0xce, 0xdb, 0x85, 0xe7, 0xe7, 0xed, 0xc2, 0x9f, 0xe7, 0xed, 0xc2, 0x37,
	0x1b, 0x2f, 0xe1, 0xe2, 0xec, 0x2f, 0x43, 0xfc, 0x26, 0xd8, 0x55, 0x21, 0xd2, 0x47, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xf5, 0xec, 0x41, 0x59, 0x0f, 0x09, 0x00, 0x00,
}

func (m *Custodian) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Custodian) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Custodian) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if len(m.BtcPubkey) > 0 {
		i -= len(m.BtcPubkey)
		copy(dAtA[i:], m.BtcPubkey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BtcPubkey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CustodianGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustodianGroup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustodianGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Custodians) > 0 {
		for iNdEx := len(m.Custodians) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Custodians[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x32
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.Quorum != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Quorum))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BtcPubkey) > 0 {
		i -= len(m.BtcPubkey)
		copy(dAtA[i:], m.BtcPubkey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BtcPubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uid) > 0 {
		i -= len(m.Uid)
		copy(dAtA[i:], m.Uid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Uid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PsbtMultiSig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PsbtMultiSig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PsbtMultiSig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TapScriptSigs) > 0 {
		keysForTapScriptSigs := make([]string, 0, len(m.TapScriptSigs))
		for k := range m.TapScriptSigs {
			keysForTapScriptSigs = append(keysForTapScriptSigs, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForTapScriptSigs)
		for iNdEx := len(keysForTapScriptSigs) - 1; iNdEx >= 0; iNdEx-- {
			v := m.TapScriptSigs[string(keysForTapScriptSigs[iNdEx])]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintTypes(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(keysForTapScriptSigs[iNdEx])
			copy(dAtA[i:], keysForTapScriptSigs[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(keysForTapScriptSigs[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintTypes(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Psbt) > 0 {
		i -= len(m.Psbt)
		copy(dAtA[i:], m.Psbt)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Psbt)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.KeyID) > 0 {
		i -= len(m.KeyID)
		copy(dAtA[i:], m.KeyID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.KeyID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Key) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Key) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Key) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.State != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.SigningThreshold.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.PubKeys) > 0 {
		keysForPubKeys := make([]string, 0, len(m.PubKeys))
		for k := range m.PubKeys {
			keysForPubKeys = append(keysForPubKeys, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForPubKeys)
		for iNdEx := len(keysForPubKeys) - 1; iNdEx >= 0; iNdEx-- {
			v := m.PubKeys[string(keysForPubKeys[iNdEx])]
			baseI := i
			if len(v) > 0 {
				i -= len(v)
				copy(dAtA[i:], v)
				i = encodeVarintTypes(dAtA, i, uint64(len(v)))
				i--
				dAtA[i] = 0x12
			}
			i -= len(keysForPubKeys[iNdEx])
			copy(dAtA[i:], keysForPubKeys[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(keysForPubKeys[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintTypes(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.Snapshot.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SigningSession) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigningSession) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigningSession) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ModuleMetadata != nil {
		{
			size, err := m.ModuleMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x4a
	}
	if m.GracePeriod != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.GracePeriod))
		i--
		dAtA[i] = 0x40
	}
	if m.CompletedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CompletedAt))
		i--
		dAtA[i] = 0x38
	}
	if m.ExpiresAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Psbt) > 0 {
		i -= len(m.Psbt)
		copy(dAtA[i:], m.Psbt)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Psbt)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.Key.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.State != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.PsbtMultiSig.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.ID != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Custodian) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BtcPubkey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *CustodianGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BtcPubkey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Quorum != 0 {
		n += 1 + sovTypes(uint64(m.Quorum))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Custodians) > 0 {
		for _, e := range m.Custodians {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *PsbtMultiSig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.KeyID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Psbt)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.TapScriptSigs) > 0 {
		for k, v := range m.TapScriptSigs {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovTypes(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovTypes(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovTypes(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *Key) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Snapshot.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.PubKeys) > 0 {
		for k, v := range m.PubKeys {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovTypes(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovTypes(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovTypes(uint64(mapEntrySize))
		}
	}
	l = m.SigningThreshold.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.State != 0 {
		n += 1 + sovTypes(uint64(m.State))
	}
	return n
}

func (m *SigningSession) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovTypes(uint64(m.ID))
	}
	l = m.PsbtMultiSig.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.State != 0 {
		n += 1 + sovTypes(uint64(m.State))
	}
	l = m.Key.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.Psbt)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovTypes(uint64(m.ExpiresAt))
	}
	if m.CompletedAt != 0 {
		n += 1 + sovTypes(uint64(m.CompletedAt))
	}
	if m.GracePeriod != 0 {
		n += 1 + sovTypes(uint64(m.GracePeriod))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ModuleMetadata != nil {
		l = m.ModuleMetadata.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Custodian) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Custodian: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Custodian: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcPubkey = append(m.BtcPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.BtcPubkey == nil {
				m.BtcPubkey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustodianGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustodianGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustodianGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quorum", wireType)
			}
			m.Quorum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quorum |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Custodians", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Custodians = append(m.Custodians, &Custodian{})
			if err := m.Custodians[len(m.Custodians)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PsbtMultiSig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PsbtMultiSig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PsbtMultiSig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyID = github_com_scalarorg_scalar_core_x_multisig_exported.KeyID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Psbt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Psbt = append(m.Psbt[:0], dAtA[iNdEx:postIndex]...)
			if m.Psbt == nil {
				m.Psbt = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TapScriptSigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TapScriptSigs == nil {
				m.TapScriptSigs = make(map[string]*exported.TapScriptSig)
			}
			var mapkey string
			var mapvalue *exported.TapScriptSig
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTypes
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthTypes
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthTypes
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthTypes
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &exported.TapScriptSig{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTypes(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthTypes
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.TapScriptSigs[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Key) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Key: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Key: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = github_com_scalarorg_scalar_core_x_multisig_exported.KeyID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubKeys == nil {
				m.PubKeys = make(map[string]github_com_scalarorg_scalar_core_x_multisig_exported.PublicKey)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTypes
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthTypes
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthTypes
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthTypes
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTypes(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthTypes
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.PubKeys[mapkey] = ((github_com_scalarorg_scalar_core_x_multisig_exported.PublicKey)(mapvalue))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigningThreshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SigningThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= exported.KeyState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigningSession) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigningSession: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigningSession: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PsbtMultiSig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PsbtMultiSig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= exported.PsbtState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Key.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Psbt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Psbt = append(m.Psbt[:0], dAtA[iNdEx:postIndex]...)
			if m.Psbt == nil {
				m.Psbt = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAt", wireType)
			}
			m.CompletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GracePeriod", wireType)
			}
			m.GracePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GracePeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ModuleMetadata == nil {
				m.ModuleMetadata = &types.Any{}
			}
			if err := m.ModuleMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
