// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scalar/chains/v1beta1/service.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("scalar/chains/v1beta1/service.proto", fileDescriptor_bd3ac3d6d884da59)
}
func init() {
	golang_proto.RegisterFile("scalar/chains/v1beta1/service.proto", fileDescriptor_bd3ac3d6d884da59)
}

var fileDescriptor_bd3ac3d6d884da59 = []byte{
	// 1228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x98, 0xcf, 0x6f, 0xdc, 0xc4,
	0x17, 0xc0, 0x33, 0x5f, 0x7d, 0x09, 0x65, 0xa8, 0x12, 0x18, 0x7e, 0x1c, 0x02, 0x2c, 0xc5, 0xf9,
	0xd1, 0x64, 0xd3, 0xb5, 0x93, 0x4d, 0x5a, 0x4a, 0x84, 0x90, 0x9a, 0xb4, 0xfc, 0x50, 0xa9, 0x08,
	0x49, 0x4f, 0x5c, 0x2c, 0xaf, 0x3d, 0xf1, 0x5a, 0xd9, 0x78, 0xb6, 0x33, 0xb3, 0x69, 0x56, 0x25,
	0x17, 0xc4, 0xa1, 0x12, 0x42, 0x2a, 0x42, 0x08, 0xb8, 0xc1, 0xa1, 0x87, 0x1e, 0xe0, 0xc6, 0xbd,
	0xdc, 0x38, 0x16, 0x71, 0x41, 0xe2, 0x82, 0x12, 0xfe, 0x10, 0xe4, 0xe7, 0x99, 0xdd, 0xb5, 0x93,
	0xb1, 0xdd, 0x72, 0x4b, 0xe2, 0xcf, 0x7b, 0xf3, 0xf1, 0x3c, 0xfb, 0xcd, 0x73, 0xf0, 0xb4, 0xf0,
	0xbd, 0x8e, 0xc7, 0x1d, 0xbf, 0xed, 0x45, 0xb1, 0x70, 0xf6, 0x97, 0x5b, 0x54, 0x7a, 0xcb, 0x8e,
	0xa0, 0x7c, 0x3f, 0xf2, 0xa9, 0xdd, 0xe5, 0x4c, 0x32, 0xf2, 0x52, 0x0a, 0xd9, 0x29, 0x64, 0x2b,
	0x68, 0xea, 0xc5, 0x90, 0x85, 0x0c, 0x08, 0x27, 0xf9, 0x29, 0x85, 0xa7, 0x5e, 0x0d, 0x19, 0x0b,
	0x3b, 0xd4, 0xf1, 0xba, 0x91, 0xe3, 0xc5, 0x31, 0x93, 0x9e, 0x8c, 0x58, 0x2c, 0xd4, 0xd5, 0x37,
	0x4e, 0x5f, 0xef, 0x56, 0x8f, 0xf2, 0xbe, 0x42, 0x6a, 0xa7, 0x23, 0xf2, 0x20, 0xbd, 0xde, 0x7c,
	0xf8, 0x02, 0xc6, 0x37, 0x44, 0xb8, 0x9d, 0x2a, 0x92, 0x07, 0x08, 0x3f, 0xb7, 0xc1, 0xe2, 0x9d,
	0x88, 0xef, 0x6d, 0xb3, 0x1e, 0xf7, 0xe9, 0xcd, 0x03, 0x41, 0x6c, 0xfb, 0x54, 0x65, 0x3b, 0x0f,
	0x6e, 0xd1, 0x5b, 0x3d, 0x2a, 0xe4, 0x94, 0x53, 0x99, 0x17, 0x5d, 0x16, 0x0b, 0x6a, 0xad, 0x7e,
	0xf6, 0xc7, 0x3f, 0x5f, 0xff, 0xcf, 0xb6, 0x16, 0x9c, 0xd3, 0x6d, 0xfd, 0x34, 0xd0, 0x15, 0x10,
	0xe9, 0xca, 0x03, 0xb1, 0x86, 0xea, 0xe4, 0x1e, 0xc2, 0x78, 0x9b, 0xca, 0xf7, 0x3c, 0x49, 0x6f,
	0x7b, 0x7d, 0x32, 0x6f, 0x58, 0x75, 0x88, 0x68, 0xbf, 0x85, 0x0a, 0xa4, 0x32, 0x6b, 0x80, 0xd9,
	0x79, 0xcb, 0x72, 0x4c, 0xa5, 0x95, 0x6e, 0x98, 0xc6, 0x24, 0x4a, 0xb7, 0xf1, 0xff, 0x3f, 0x8c,
	0xe2, 0x5d, 0x62, 0x19, 0x56, 0x48, 0x2e, 0x6a, 0x8b, 0xe9, 0x42, 0x46, 0xad, 0x3f, 0x07, 0xeb,
	0x9f, 0xb3, 0x5e, 0x31, 0xac, 0xdf, 0x89, 0xe2, 0xdd, 0x64, 0xe1, 0xef, 0x10, 0x3e, 0xab, 0xb6,
	0xf7, 0x26, 0xdb, 0xa5, 0x31, 0xa9, 0x17, 0xd7, 0x00, 0x20, 0x6d, 0xb2, 0x58, 0x89, 0x55, 0x46,
	0x0e, 0x18, 0x2d, 0x58, 0x33, 0x25, 0xb5, 0x92, 0x49, 0x54, 0xa2, 0xf6, 0x03, 0xc2, 0x13, 0x2a,
	0xd3, 0x55, 0xda, 0x65, 0x22, 0x92, 0xe4, 0x42, 0xf1, 0x82, 0x0a, 0xd3, 0x7a, 0x8d, 0x8a, 0xb4,
	0x12, 0x5c, 0x06, 0xc1, 0x45, 0x6b, 0xae, 0x44, 0x30, 0x48, 0xe3, 0x12, 0xc5, 0x07, 0x08, 0x13,
	0x7d, 0xb3, 0xdc, 0x8b, 0xc5, 0x0e, 0xe5, 0xd7, 0x69, 0x9f, 0x2c, 0x95, 0xec, 0xcb, 0x10, 0xd5,
	0xaa, 0xcb, 0x8f, 0x11, 0xa1, 0x74, 0x6d, 0xd0, 0x9d, 0xb7, 0xa6, 0x73, 0xba, 0x83, 0x7d, 0x54,
	0x31, 0xee, 0x2e, 0x85, 0x47, 0xec, 0x27, 0x84, 0x9f, 0xdf, 0xe0, 0xd4, 0x93, 0xf4, 0x2a, 0xed,
	0x76, 0x58, 0x3f, 0x2d, 0xb7, 0xf1, 0x95, 0xcb, 0x93, 0xda, 0x74, 0xa9, 0x7a, 0x80, 0x12, 0xbd,
	0x08, 0xa2, 0x8e, 0x55, 0x37, 0xed, 0x2b, 0x44, 0x26, 0xdb, 0xda, 0x61, 0xfd, 0x61, 0xf9, 0xa1,
	0xa3, 0xc0, 0xa5, 0xf5, 0x1e, 0x8f, 0x21, 0x65, 0x41, 0x47, 0xc9, 0x81, 0xa5, 0x1d, 0xe5, 0x04,
	0x5f, 0xb5, 0xa3, 0xa4, 0xb2, 0xad, 0x1e, 0x8f, 0x53, 0x55, 0xe8, 0x28, 0xbf, 0x22, 0xfc, 0x72,
	0x9a, 0x72, 0x93, 0xc6, 0x41, 0x14, 0x87, 0xba, 0x60, 0x82, 0xac, 0x16, 0x1a, 0xe4, 0x71, 0xed,
	0x7d, 0xf1, 0x31, 0xa3, 0x94, 0xfd, 0x1a, 0xd8, 0xaf, 0x5a, 0x4e, 0xb1, 0x7d, 0x37, 0x8d, 0x1f,
	0x3c, 0x22, 0x70, 0x0f, 0xbf, 0x23, 0x3c, 0x95, 0xa6, 0xd7, 0x79, 0x3f, 0xea, 0x52, 0xee, 0x49,
	0xc6, 0x45, 0x3b, 0xea, 0x92, 0xcb, 0x85, 0x46, 0xa7, 0x85, 0xe8, 0x7b, 0x79, 0xeb, 0x09, 0x22,
	0xd5, 0xfd, 0xbc, 0x03, 0xf7, 0x73, 0xd9, 0x5a, 0x29, 0xbe, 0x9f, 0xc1, 0xa3, 0xce, 0x46, 0x92,
	0xe8, 0xee, 0xb6, 0x1d, 0x85, 0xf1, 0x06, 0xdb, 0xdb, 0xf3, 0xe2, 0x40, 0x18, 0xbb, 0xdb, 0x28,
	0x54, 0xd6, 0xdd, 0xb2, 0x6c, 0xc5, 0xee, 0x26, 0xa2, 0x30, 0x76, 0x7d, 0x15, 0x95, 0xa8, 0xfd,
	0x88, 0xf0, 0x44, 0x92, 0x69, 0x5d, 0xfa, 0x2a, 0x19, 0x69, 0x14, 0x2c, 0x38, 0xc4, 0x9e, 0xcc,
	0x6f, 0x05, 0xfc, 0x1a, 0xd6, 0x7c, 0x91, 0x5f, 0x4b, 0xfa, 0x19, 0xc7, 0xfb, 0x08, 0x4f, 0x26,
	0xd9, 0x36, 0x45, 0x4b, 0x56, 0x91, 0x1c, 0xe1, 0xb4, 0xa4, 0x5d, 0x15, 0xff, 0x2f, 0x9e, 0x77,
	0x11, 0x3e, 0x73, 0x25, 0x08, 0x36, 0x12, 0x94, 0xcc, 0x19, 0x56, 0xd4, 0x80, 0x36, 0x3b, 0x5f,
	0xca, 0x29, 0xa5, 0x45, 0x50, 0x9a, 0xb5, 0xce, 0x19, 0x94, 0xbc, 0x20, 0x70, 0xe1, 0x4f, 0xba,
	0x6b, 0x6d, 0x51, 0xc9, 0xfb, 0xef, 0x7a, 0x51, 0x87, 0x06, 0xd7, 0xf6, 0x69, 0x2c, 0x8d, 0x5d,
	0x2b, 0x0f, 0x96, 0x75, 0xad, 0x93, 0x7c, 0xc5, 0xae, 0xc5, 0x93, 0xc0, 0xc6, 0x0e, 0x44, 0x36,
	0x68, 0x12, 0xba, 0x86, 0xea, 0xcd, 0xbf, 0x26, 0xf1, 0xd9, 0x8f, 0x93, 0x91, 0x4f, 0x0f, 0x71,
	0x3f, 0x23, 0x3c, 0xb9, 0xee, 0x49, 0xbf, 0x4d, 0x83, 0xc1, 0x1b, 0x63, 0xaa, 0x77, 0x8e, 0x2b,
	0xab, 0xf7, 0x09, 0x5c, 0x99, 0xbf, 0x0d, 0xe6, 0x97, 0xc8, 0xaa, 0xc1, 0xbc, 0x95, 0xc6, 0x0d,
	0xca, 0xed, 0xdc, 0x01, 0xe0, 0xd0, 0xb9, 0x13, 0x05, 0x87, 0xe4, 0x4b, 0x84, 0x71, 0xd2, 0xc4,
	0x29, 0xff, 0x20, 0xde, 0x61, 0xc6, 0x49, 0x6e, 0x88, 0x94, 0x4d, 0x72, 0xa3, 0xa4, 0x32, 0xac,
	0x83, 0xe1, 0x0c, 0x31, 0x4d, 0x72, 0x2d, 0x08, 0x71, 0xa3, 0x44, 0xe0, 0x97, 0xe1, 0x3c, 0x00,
	0xf3, 0xf6, 0xfb, 0x34, 0x0a, 0xdb, 0xb2, 0x6c, 0x1e, 0x18, 0x41, 0x2b, 0xce, 0x03, 0x99, 0x88,
	0x6c, 0xef, 0x27, 0xcd, 0xe2, 0xf1, 0x05, 0x42, 0xdd, 0x36, 0xc4, 0xea, 0xcd, 0x4c, 0x9e, 0xda,
	0x49, 0x75, 0xa8, 0x94, 0x16, 0x3e, 0xc7, 0x95, 0x15, 0xfe, 0x04, 0xae, 0x74, 0xdf, 0x04, 0xdd,
	0x65, 0x62, 0x3a, 0xaa, 0xf4, 0x19, 0x95, 0x2f, 0x3c, 0xf9, 0x14, 0x8f, 0xc3, 0xfb, 0x29, 0xc8,
	0x8c, 0x69, 0x93, 0xe0, 0x57, 0x2d, 0x36, 0x5b, 0x42, 0x29, 0x9f, 0x59, 0xf0, 0x79, 0x9d, 0xbc,
	0x66, 0xda, 0xbe, 0x74, 0xcd, 0xbb, 0x08, 0x3f, 0xad, 0x5b, 0xa1, 0x31, 0x73, 0xb6, 0x05, 0xce,
	0x95, 0x61, 0xd9, 0x81, 0x8e, 0x98, 0xe7, 0x4f, 0xe0, 0x5d, 0x9e, 0xe6, 0x25, 0xdf, 0x20, 0x8c,
	0xaf, 0xd3, 0xfe, 0x95, 0x20, 0xe0, 0x54, 0x08, 0xe3, 0xc3, 0x3f, 0x44, 0xca, 0x1e, 0xfe, 0x51,
	0x52, 0x39, 0x35, 0xc1, 0xe9, 0x02, 0x31, 0xcd, 0x6e, 0xbb, 0xb4, 0xef, 0x7a, 0x69, 0xcc, 0xa0,
	0x40, 0xf7, 0x11, 0x9e, 0x50, 0x9f, 0x43, 0xda, 0xcd, 0x34, 0xb7, 0x67, 0xb1, 0xb2, 0xb9, 0x3d,
	0x4f, 0x2b, 0xc7, 0x4b, 0xe0, 0xb8, 0x44, 0x6c, 0x83, 0xa3, 0xfa, 0xcc, 0x3a, 0xe1, 0xf9, 0x2d,
	0xc2, 0x67, 0xd6, 0xfb, 0x92, 0xfa, 0x2c, 0xa0, 0xc6, 0x53, 0x43, 0x03, 0x65, 0xa7, 0xc6, 0x90,
	0xab, 0xf8, 0x3a, 0xb6, 0x54, 0xc0, 0xb0, 0xa1, 0xf9, 0x2c, 0x96, 0xdc, 0xf3, 0xe5, 0x21, 0xf9,
	0x02, 0xe1, 0xa7, 0xd2, 0x93, 0xc3, 0xf4, 0xad, 0x97, 0x39, 0x2e, 0x66, 0x8a, 0xa1, 0x8a, 0x2f,
	0x1c, 0x1c, 0x0b, 0x43, 0x1b, 0xf8, 0xd5, 0x4d, 0x9a, 0xec, 0xf7, 0x08, 0x3f, 0x7b, 0x6d, 0x6b,
	0xa3, 0xb9, 0xa4, 0x66, 0x70, 0xd3, 0xe3, 0x33, 0xc2, 0x68, 0xb3, 0x7a, 0x15, 0x34, 0x7b, 0xf2,
	0x93, 0x45, 0x93, 0x1f, 0xf7, 0x9b, 0x4b, 0x6a, 0xe6, 0x1e, 0xd4, 0xf0, 0x2b, 0x84, 0x9f, 0x81,
	0x3c, 0xd0, 0xff, 0x4d, 0xc5, 0x19, 0x10, 0xda, 0x6b, 0xbe, 0x1c, 0xcc, 0x7e, 0x14, 0x12, 0xd3,
	0xc9, 0x0a, 0x3e, 0xd0, 0xfc, 0x07, 0x4e, 0x9f, 0x23, 0x3c, 0xbe, 0xe9, 0x71, 0x6f, 0xcf, 0xdc,
	0xa1, 0xd2, 0xcb, 0x65, 0x1d, 0x4a, 0x53, 0xd9, 0x7f, 0x29, 0x90, 0x59, 0x53, 0xc7, 0x04, 0x5c,
	0x6b, 0xac, 0xdf, 0xf8, 0xed, 0xa8, 0x86, 0x1e, 0x1d, 0xd5, 0xd0, 0xdf, 0x47, 0x35, 0x74, 0xef,
	0xb8, 0x36, 0xf6, 0xf0, 0xb8, 0x86, 0x1e, 0x1d, 0xd7, 0xc6, 0xfe, 0x3c, 0xae, 0x8d, 0x7d, 0xe2,
	0x84, 0x91, 0x6c, 0xf7, 0x5a, 0xb6, 0xcf, 0xf6, 0x54, 0x3a, 0xc6, 0x43, 0xf5, 0x53, 0xc3, 0x67,
	0x9c, 0x3a, 0x07, 0x3a, 0xbf, 0xec, 0x77, 0xa9, 0x68, 0x8d, 0xc3, 0xbf, 0x7d, 0x56, 0xfe, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x22, 0x71, 0xc8, 0x21, 0xab, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgServiceClient interface {
	ConfirmSourceTxs(ctx context.Context, in *ConfirmSourceTxsRequest, opts ...grpc.CallOption) (*ConfirmSourceTxsResponse, error)
	SetGateway(ctx context.Context, in *SetGatewayRequest, opts ...grpc.CallOption) (*SetGatewayResponse, error)
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*LinkResponse, error)
	ConfirmToken(ctx context.Context, in *ConfirmTokenRequest, opts ...grpc.CallOption) (*ConfirmTokenResponse, error)
	ConfirmDeposit(ctx context.Context, in *ConfirmDepositRequest, opts ...grpc.CallOption) (*ConfirmDepositResponse, error)
	ConfirmTransferKey(ctx context.Context, in *ConfirmTransferKeyRequest, opts ...grpc.CallOption) (*ConfirmTransferKeyResponse, error)
	CreateDeployToken(ctx context.Context, in *CreateDeployTokenRequest, opts ...grpc.CallOption) (*CreateDeployTokenResponse, error)
	CreateBurnTokens(ctx context.Context, in *CreateBurnTokensRequest, opts ...grpc.CallOption) (*CreateBurnTokensResponse, error)
	CreatePendingTransfers(ctx context.Context, in *CreatePendingTransfersRequest, opts ...grpc.CallOption) (*CreatePendingTransfersResponse, error)
	CreateTransferOperatorship(ctx context.Context, in *CreateTransferOperatorshipRequest, opts ...grpc.CallOption) (*CreateTransferOperatorshipResponse, error)
	SignCommands(ctx context.Context, in *SignCommandsRequest, opts ...grpc.CallOption) (*SignCommandsResponse, error)
	SignBtcCommand(ctx context.Context, in *SignBtcCommandsRequest, opts ...grpc.CallOption) (*SignCommandsResponse, error)
	SignPsbtCommand(ctx context.Context, in *SignPsbtCommandRequest, opts ...grpc.CallOption) (*SignPsbtCommandResponse, error)
	AddChain(ctx context.Context, in *AddChainRequest, opts ...grpc.CallOption) (*AddChainResponse, error)
	RetryFailedEvent(ctx context.Context, in *RetryFailedEventRequest, opts ...grpc.CallOption) (*RetryFailedEventResponse, error)
}

type msgServiceClient struct {
	cc grpc1.ClientConn
}

func NewMsgServiceClient(cc grpc1.ClientConn) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) ConfirmSourceTxs(ctx context.Context, in *ConfirmSourceTxsRequest, opts ...grpc.CallOption) (*ConfirmSourceTxsResponse, error) {
	out := new(ConfirmSourceTxsResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/ConfirmSourceTxs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) SetGateway(ctx context.Context, in *SetGatewayRequest, opts ...grpc.CallOption) (*SetGatewayResponse, error) {
	out := new(SetGatewayResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/SetGateway", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*LinkResponse, error) {
	out := new(LinkResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/Link", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ConfirmToken(ctx context.Context, in *ConfirmTokenRequest, opts ...grpc.CallOption) (*ConfirmTokenResponse, error) {
	out := new(ConfirmTokenResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/ConfirmToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ConfirmDeposit(ctx context.Context, in *ConfirmDepositRequest, opts ...grpc.CallOption) (*ConfirmDepositResponse, error) {
	out := new(ConfirmDepositResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/ConfirmDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ConfirmTransferKey(ctx context.Context, in *ConfirmTransferKeyRequest, opts ...grpc.CallOption) (*ConfirmTransferKeyResponse, error) {
	out := new(ConfirmTransferKeyResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/ConfirmTransferKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateDeployToken(ctx context.Context, in *CreateDeployTokenRequest, opts ...grpc.CallOption) (*CreateDeployTokenResponse, error) {
	out := new(CreateDeployTokenResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/CreateDeployToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateBurnTokens(ctx context.Context, in *CreateBurnTokensRequest, opts ...grpc.CallOption) (*CreateBurnTokensResponse, error) {
	out := new(CreateBurnTokensResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/CreateBurnTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreatePendingTransfers(ctx context.Context, in *CreatePendingTransfersRequest, opts ...grpc.CallOption) (*CreatePendingTransfersResponse, error) {
	out := new(CreatePendingTransfersResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/CreatePendingTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) CreateTransferOperatorship(ctx context.Context, in *CreateTransferOperatorshipRequest, opts ...grpc.CallOption) (*CreateTransferOperatorshipResponse, error) {
	out := new(CreateTransferOperatorshipResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/CreateTransferOperatorship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) SignCommands(ctx context.Context, in *SignCommandsRequest, opts ...grpc.CallOption) (*SignCommandsResponse, error) {
	out := new(SignCommandsResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/SignCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) SignBtcCommand(ctx context.Context, in *SignBtcCommandsRequest, opts ...grpc.CallOption) (*SignCommandsResponse, error) {
	out := new(SignCommandsResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/SignBtcCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) SignPsbtCommand(ctx context.Context, in *SignPsbtCommandRequest, opts ...grpc.CallOption) (*SignPsbtCommandResponse, error) {
	out := new(SignPsbtCommandResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/SignPsbtCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) AddChain(ctx context.Context, in *AddChainRequest, opts ...grpc.CallOption) (*AddChainResponse, error) {
	out := new(AddChainResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/AddChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) RetryFailedEvent(ctx context.Context, in *RetryFailedEventRequest, opts ...grpc.CallOption) (*RetryFailedEventResponse, error) {
	out := new(RetryFailedEventResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.MsgService/RetryFailedEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServiceServer is the server API for MsgService service.
type MsgServiceServer interface {
	ConfirmSourceTxs(context.Context, *ConfirmSourceTxsRequest) (*ConfirmSourceTxsResponse, error)
	SetGateway(context.Context, *SetGatewayRequest) (*SetGatewayResponse, error)
	Link(context.Context, *LinkRequest) (*LinkResponse, error)
	ConfirmToken(context.Context, *ConfirmTokenRequest) (*ConfirmTokenResponse, error)
	ConfirmDeposit(context.Context, *ConfirmDepositRequest) (*ConfirmDepositResponse, error)
	ConfirmTransferKey(context.Context, *ConfirmTransferKeyRequest) (*ConfirmTransferKeyResponse, error)
	CreateDeployToken(context.Context, *CreateDeployTokenRequest) (*CreateDeployTokenResponse, error)
	CreateBurnTokens(context.Context, *CreateBurnTokensRequest) (*CreateBurnTokensResponse, error)
	CreatePendingTransfers(context.Context, *CreatePendingTransfersRequest) (*CreatePendingTransfersResponse, error)
	CreateTransferOperatorship(context.Context, *CreateTransferOperatorshipRequest) (*CreateTransferOperatorshipResponse, error)
	SignCommands(context.Context, *SignCommandsRequest) (*SignCommandsResponse, error)
	SignBtcCommand(context.Context, *SignBtcCommandsRequest) (*SignCommandsResponse, error)
	SignPsbtCommand(context.Context, *SignPsbtCommandRequest) (*SignPsbtCommandResponse, error)
	AddChain(context.Context, *AddChainRequest) (*AddChainResponse, error)
	RetryFailedEvent(context.Context, *RetryFailedEventRequest) (*RetryFailedEventResponse, error)
}

// UnimplementedMsgServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServiceServer struct {
}

func (*UnimplementedMsgServiceServer) ConfirmSourceTxs(ctx context.Context, req *ConfirmSourceTxsRequest) (*ConfirmSourceTxsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmSourceTxs not implemented")
}
func (*UnimplementedMsgServiceServer) SetGateway(ctx context.Context, req *SetGatewayRequest) (*SetGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGateway not implemented")
}
func (*UnimplementedMsgServiceServer) Link(ctx context.Context, req *LinkRequest) (*LinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Link not implemented")
}
func (*UnimplementedMsgServiceServer) ConfirmToken(ctx context.Context, req *ConfirmTokenRequest) (*ConfirmTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmToken not implemented")
}
func (*UnimplementedMsgServiceServer) ConfirmDeposit(ctx context.Context, req *ConfirmDepositRequest) (*ConfirmDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmDeposit not implemented")
}
func (*UnimplementedMsgServiceServer) ConfirmTransferKey(ctx context.Context, req *ConfirmTransferKeyRequest) (*ConfirmTransferKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTransferKey not implemented")
}
func (*UnimplementedMsgServiceServer) CreateDeployToken(ctx context.Context, req *CreateDeployTokenRequest) (*CreateDeployTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeployToken not implemented")
}
func (*UnimplementedMsgServiceServer) CreateBurnTokens(ctx context.Context, req *CreateBurnTokensRequest) (*CreateBurnTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBurnTokens not implemented")
}
func (*UnimplementedMsgServiceServer) CreatePendingTransfers(ctx context.Context, req *CreatePendingTransfersRequest) (*CreatePendingTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePendingTransfers not implemented")
}
func (*UnimplementedMsgServiceServer) CreateTransferOperatorship(ctx context.Context, req *CreateTransferOperatorshipRequest) (*CreateTransferOperatorshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransferOperatorship not implemented")
}
func (*UnimplementedMsgServiceServer) SignCommands(ctx context.Context, req *SignCommandsRequest) (*SignCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignCommands not implemented")
}
func (*UnimplementedMsgServiceServer) SignBtcCommand(ctx context.Context, req *SignBtcCommandsRequest) (*SignCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBtcCommand not implemented")
}
func (*UnimplementedMsgServiceServer) SignPsbtCommand(ctx context.Context, req *SignPsbtCommandRequest) (*SignPsbtCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignPsbtCommand not implemented")
}
func (*UnimplementedMsgServiceServer) AddChain(ctx context.Context, req *AddChainRequest) (*AddChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChain not implemented")
}
func (*UnimplementedMsgServiceServer) RetryFailedEvent(ctx context.Context, req *RetryFailedEventRequest) (*RetryFailedEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryFailedEvent not implemented")
}

func RegisterMsgServiceServer(s grpc1.Server, srv MsgServiceServer) {
	s.RegisterService(&_MsgService_serviceDesc, srv)
}

func _MsgService_ConfirmSourceTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmSourceTxsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmSourceTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/ConfirmSourceTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmSourceTxs(ctx, req.(*ConfirmSourceTxsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_SetGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SetGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/SetGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SetGateway(ctx, req.(*SetGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/Link",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).Link(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ConfirmToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/ConfirmToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmToken(ctx, req.(*ConfirmTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ConfirmDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/ConfirmDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmDeposit(ctx, req.(*ConfirmDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ConfirmTransferKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTransferKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ConfirmTransferKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/ConfirmTransferKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ConfirmTransferKey(ctx, req.(*ConfirmTransferKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateDeployToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeployTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateDeployToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/CreateDeployToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateDeployToken(ctx, req.(*CreateDeployTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateBurnTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBurnTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateBurnTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/CreateBurnTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateBurnTokens(ctx, req.(*CreateBurnTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreatePendingTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePendingTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreatePendingTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/CreatePendingTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreatePendingTransfers(ctx, req.(*CreatePendingTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_CreateTransferOperatorship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferOperatorshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).CreateTransferOperatorship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/CreateTransferOperatorship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).CreateTransferOperatorship(ctx, req.(*CreateTransferOperatorshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_SignCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SignCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/SignCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SignCommands(ctx, req.(*SignCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_SignBtcCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignBtcCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SignBtcCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/SignBtcCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SignBtcCommand(ctx, req.(*SignBtcCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_SignPsbtCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignPsbtCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SignPsbtCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/SignPsbtCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SignPsbtCommand(ctx, req.(*SignPsbtCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_AddChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).AddChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/AddChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).AddChain(ctx, req.(*AddChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_RetryFailedEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryFailedEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).RetryFailedEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.MsgService/RetryFailedEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).RetryFailedEvent(ctx, req.(*RetryFailedEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scalar.chains.v1beta1.MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmSourceTxs",
			Handler:    _MsgService_ConfirmSourceTxs_Handler,
		},
		{
			MethodName: "SetGateway",
			Handler:    _MsgService_SetGateway_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _MsgService_Link_Handler,
		},
		{
			MethodName: "ConfirmToken",
			Handler:    _MsgService_ConfirmToken_Handler,
		},
		{
			MethodName: "ConfirmDeposit",
			Handler:    _MsgService_ConfirmDeposit_Handler,
		},
		{
			MethodName: "ConfirmTransferKey",
			Handler:    _MsgService_ConfirmTransferKey_Handler,
		},
		{
			MethodName: "CreateDeployToken",
			Handler:    _MsgService_CreateDeployToken_Handler,
		},
		{
			MethodName: "CreateBurnTokens",
			Handler:    _MsgService_CreateBurnTokens_Handler,
		},
		{
			MethodName: "CreatePendingTransfers",
			Handler:    _MsgService_CreatePendingTransfers_Handler,
		},
		{
			MethodName: "CreateTransferOperatorship",
			Handler:    _MsgService_CreateTransferOperatorship_Handler,
		},
		{
			MethodName: "SignCommands",
			Handler:    _MsgService_SignCommands_Handler,
		},
		{
			MethodName: "SignBtcCommand",
			Handler:    _MsgService_SignBtcCommand_Handler,
		},
		{
			MethodName: "SignPsbtCommand",
			Handler:    _MsgService_SignPsbtCommand_Handler,
		},
		{
			MethodName: "AddChain",
			Handler:    _MsgService_AddChain_Handler,
		},
		{
			MethodName: "RetryFailedEvent",
			Handler:    _MsgService_RetryFailedEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scalar/chains/v1beta1/service.proto",
}

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryServiceClient interface {
	// BatchedCommands queries the batched commands for a specified chain and
	// BatchedCommandsID if no BatchedCommandsID is specified, then it returns the
	// latest batched commands
	BatchedCommands(ctx context.Context, in *BatchedCommandsRequest, opts ...grpc.CallOption) (*BatchedCommandsResponse, error)
	BurnerInfo(ctx context.Context, in *BurnerInfoRequest, opts ...grpc.CallOption) (*BurnerInfoResponse, error)
	// ConfirmationHeight queries the confirmation height for the specified chain
	ConfirmationHeight(ctx context.Context, in *ConfirmationHeightRequest, opts ...grpc.CallOption) (*ConfirmationHeightResponse, error)
	// PendingCommands queries the pending commands for the specified chain
	PendingCommands(ctx context.Context, in *PendingCommandsRequest, opts ...grpc.CallOption) (*PendingCommandsResponse, error)
	// Chains queries the available chains
	Chains(ctx context.Context, in *ChainsRequest, opts ...grpc.CallOption) (*ChainsResponse, error)
	// Command queries the command of a chain provided the command id
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// KeyAddress queries the address of key of a chain
	KeyAddress(ctx context.Context, in *KeyAddressRequest, opts ...grpc.CallOption) (*KeyAddressResponse, error)
	// GatewayAddress queries the address of scalar gateway at the specified
	// chain
	GatewayAddress(ctx context.Context, in *GatewayAddressRequest, opts ...grpc.CallOption) (*GatewayAddressResponse, error)
	// Bytecode queries the bytecode of a specified gateway at the specified
	// chain
	Bytecode(ctx context.Context, in *BytecodeRequest, opts ...grpc.CallOption) (*BytecodeResponse, error)
	// Event queries an event at the specified chain
	Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	// ERC20Tokens queries the ERC20 tokens registered for a chain
	ERC20Tokens(ctx context.Context, in *ERC20TokensRequest, opts ...grpc.CallOption) (*ERC20TokensResponse, error)
	// TokenInfo queries the token info for a registered ERC20 Token
	TokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error)
	Params(ctx context.Context, in *ParamsRequest, opts ...grpc.CallOption) (*ParamsResponse, error)
}

type queryServiceClient struct {
	cc grpc1.ClientConn
}

func NewQueryServiceClient(cc grpc1.ClientConn) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) BatchedCommands(ctx context.Context, in *BatchedCommandsRequest, opts ...grpc.CallOption) (*BatchedCommandsResponse, error) {
	out := new(BatchedCommandsResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/BatchedCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) BurnerInfo(ctx context.Context, in *BurnerInfoRequest, opts ...grpc.CallOption) (*BurnerInfoResponse, error) {
	out := new(BurnerInfoResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/BurnerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ConfirmationHeight(ctx context.Context, in *ConfirmationHeightRequest, opts ...grpc.CallOption) (*ConfirmationHeightResponse, error) {
	out := new(ConfirmationHeightResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/ConfirmationHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) PendingCommands(ctx context.Context, in *PendingCommandsRequest, opts ...grpc.CallOption) (*PendingCommandsResponse, error) {
	out := new(PendingCommandsResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/PendingCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Chains(ctx context.Context, in *ChainsRequest, opts ...grpc.CallOption) (*ChainsResponse, error) {
	out := new(ChainsResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/Chains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/Command", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) KeyAddress(ctx context.Context, in *KeyAddressRequest, opts ...grpc.CallOption) (*KeyAddressResponse, error) {
	out := new(KeyAddressResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/KeyAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GatewayAddress(ctx context.Context, in *GatewayAddressRequest, opts ...grpc.CallOption) (*GatewayAddressResponse, error) {
	out := new(GatewayAddressResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/GatewayAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Bytecode(ctx context.Context, in *BytecodeRequest, opts ...grpc.CallOption) (*BytecodeResponse, error) {
	out := new(BytecodeResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/Bytecode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/Event", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ERC20Tokens(ctx context.Context, in *ERC20TokensRequest, opts ...grpc.CallOption) (*ERC20TokensResponse, error) {
	out := new(ERC20TokensResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/ERC20Tokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) TokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error) {
	out := new(TokenInfoResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/TokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) Params(ctx context.Context, in *ParamsRequest, opts ...grpc.CallOption) (*ParamsResponse, error) {
	out := new(ParamsResponse)
	err := c.cc.Invoke(ctx, "/scalar.chains.v1beta1.QueryService/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
type QueryServiceServer interface {
	// BatchedCommands queries the batched commands for a specified chain and
	// BatchedCommandsID if no BatchedCommandsID is specified, then it returns the
	// latest batched commands
	BatchedCommands(context.Context, *BatchedCommandsRequest) (*BatchedCommandsResponse, error)
	BurnerInfo(context.Context, *BurnerInfoRequest) (*BurnerInfoResponse, error)
	// ConfirmationHeight queries the confirmation height for the specified chain
	ConfirmationHeight(context.Context, *ConfirmationHeightRequest) (*ConfirmationHeightResponse, error)
	// PendingCommands queries the pending commands for the specified chain
	PendingCommands(context.Context, *PendingCommandsRequest) (*PendingCommandsResponse, error)
	// Chains queries the available chains
	Chains(context.Context, *ChainsRequest) (*ChainsResponse, error)
	// Command queries the command of a chain provided the command id
	Command(context.Context, *CommandRequest) (*CommandResponse, error)
	// KeyAddress queries the address of key of a chain
	KeyAddress(context.Context, *KeyAddressRequest) (*KeyAddressResponse, error)
	// GatewayAddress queries the address of scalar gateway at the specified
	// chain
	GatewayAddress(context.Context, *GatewayAddressRequest) (*GatewayAddressResponse, error)
	// Bytecode queries the bytecode of a specified gateway at the specified
	// chain
	Bytecode(context.Context, *BytecodeRequest) (*BytecodeResponse, error)
	// Event queries an event at the specified chain
	Event(context.Context, *EventRequest) (*EventResponse, error)
	// ERC20Tokens queries the ERC20 tokens registered for a chain
	ERC20Tokens(context.Context, *ERC20TokensRequest) (*ERC20TokensResponse, error)
	// TokenInfo queries the token info for a registered ERC20 Token
	TokenInfo(context.Context, *TokenInfoRequest) (*TokenInfoResponse, error)
	Params(context.Context, *ParamsRequest) (*ParamsResponse, error)
}

// UnimplementedQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServiceServer struct {
}

func (*UnimplementedQueryServiceServer) BatchedCommands(ctx context.Context, req *BatchedCommandsRequest) (*BatchedCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchedCommands not implemented")
}
func (*UnimplementedQueryServiceServer) BurnerInfo(ctx context.Context, req *BurnerInfoRequest) (*BurnerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnerInfo not implemented")
}
func (*UnimplementedQueryServiceServer) ConfirmationHeight(ctx context.Context, req *ConfirmationHeightRequest) (*ConfirmationHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmationHeight not implemented")
}
func (*UnimplementedQueryServiceServer) PendingCommands(ctx context.Context, req *PendingCommandsRequest) (*PendingCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingCommands not implemented")
}
func (*UnimplementedQueryServiceServer) Chains(ctx context.Context, req *ChainsRequest) (*ChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chains not implemented")
}
func (*UnimplementedQueryServiceServer) Command(ctx context.Context, req *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}
func (*UnimplementedQueryServiceServer) KeyAddress(ctx context.Context, req *KeyAddressRequest) (*KeyAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyAddress not implemented")
}
func (*UnimplementedQueryServiceServer) GatewayAddress(ctx context.Context, req *GatewayAddressRequest) (*GatewayAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewayAddress not implemented")
}
func (*UnimplementedQueryServiceServer) Bytecode(ctx context.Context, req *BytecodeRequest) (*BytecodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bytecode not implemented")
}
func (*UnimplementedQueryServiceServer) Event(ctx context.Context, req *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Event not implemented")
}
func (*UnimplementedQueryServiceServer) ERC20Tokens(ctx context.Context, req *ERC20TokensRequest) (*ERC20TokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ERC20Tokens not implemented")
}
func (*UnimplementedQueryServiceServer) TokenInfo(ctx context.Context, req *TokenInfoRequest) (*TokenInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenInfo not implemented")
}
func (*UnimplementedQueryServiceServer) Params(ctx context.Context, req *ParamsRequest) (*ParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServiceServer(s grpc1.Server, srv QueryServiceServer) {
	s.RegisterService(&_QueryService_serviceDesc, srv)
}

func _QueryService_BatchedCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchedCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).BatchedCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/BatchedCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).BatchedCommands(ctx, req.(*BatchedCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_BurnerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BurnerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).BurnerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/BurnerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).BurnerInfo(ctx, req.(*BurnerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ConfirmationHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ConfirmationHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/ConfirmationHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ConfirmationHeight(ctx, req.(*ConfirmationHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_PendingCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).PendingCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/PendingCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).PendingCommands(ctx, req.(*PendingCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Chains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Chains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/Chains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Chains(ctx, req.(*ChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_KeyAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).KeyAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/KeyAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).KeyAddress(ctx, req.(*KeyAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GatewayAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GatewayAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/GatewayAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GatewayAddress(ctx, req.(*GatewayAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Bytecode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Bytecode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/Bytecode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Bytecode(ctx, req.(*BytecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Event_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Event(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/Event",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Event(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ERC20Tokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ERC20TokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ERC20Tokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/ERC20Tokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ERC20Tokens(ctx, req.(*ERC20TokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_TokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).TokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/TokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).TokenInfo(ctx, req.(*TokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalar.chains.v1beta1.QueryService/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).Params(ctx, req.(*ParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scalar.chains.v1beta1.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchedCommands",
			Handler:    _QueryService_BatchedCommands_Handler,
		},
		{
			MethodName: "BurnerInfo",
			Handler:    _QueryService_BurnerInfo_Handler,
		},
		{
			MethodName: "ConfirmationHeight",
			Handler:    _QueryService_ConfirmationHeight_Handler,
		},
		{
			MethodName: "PendingCommands",
			Handler:    _QueryService_PendingCommands_Handler,
		},
		{
			MethodName: "Chains",
			Handler:    _QueryService_Chains_Handler,
		},
		{
			MethodName: "Command",
			Handler:    _QueryService_Command_Handler,
		},
		{
			MethodName: "KeyAddress",
			Handler:    _QueryService_KeyAddress_Handler,
		},
		{
			MethodName: "GatewayAddress",
			Handler:    _QueryService_GatewayAddress_Handler,
		},
		{
			MethodName: "Bytecode",
			Handler:    _QueryService_Bytecode_Handler,
		},
		{
			MethodName: "Event",
			Handler:    _QueryService_Event_Handler,
		},
		{
			MethodName: "ERC20Tokens",
			Handler:    _QueryService_ERC20Tokens_Handler,
		},
		{
			MethodName: "TokenInfo",
			Handler:    _QueryService_TokenInfo_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _QueryService_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scalar/chains/v1beta1/service.proto",
}
